"""
Generate a new prompts_<model>_causallm.py file, following the exact
structure of the existing hand-written prompts_qwen3_causallm.py /
prompts_gemma3_causallm.py modules.

This module only WRITES new files under prompts_generated/. It never
touches the existing prompts_qwen3_causallm.py or prompts_gemma3_causallm.py.
"""
import os
from typing import Dict, List, Optional
from dataclasses import dataclass, field

from .reference_extractor import ExtractedPattern

_GENERATED_DIR = os.path.join(
    os.path.dirname(__file__), "..", "..", "prompts_generated"
)


@dataclass
class PromptGenerationInput:
    """Everything needed to render a new prompt module"""
    model_name: str                       # e.g. "mistral7b"
    class_prefix: str                     # e.g. "Mistral7b" -> Mistral7bTransformer
    architecture_notes: List[str] = field(default_factory=list)
    patterns: Dict[str, ExtractedPattern] = field(default_factory=dict)
    constants: Dict[str, str] = field(default_factory=dict)
    forbidden_patterns: List[str] = field(default_factory=list)
    source: str = "reference"             # 'reference' | 'llm_generated'
    source_path: Optional[str] = None     # path to reference .cpp, if any


class PromptGenerator:
    """Renders a PromptGenerationInput into a complete Python module string"""

    def __init__(self, gen_input: PromptGenerationInput):
        self.inp = gen_input

    def render(self) -> str:
        model = self.inp.model_name
        upper_model = model.upper()

        worked_examples = self._render_worked_examples()
        example_names = [f"{upper_model}_{key.upper()}_EXAMPLE" for key in self.inp.patterns]

        header = self._render_header()
        constraints_fn = self._render_constraints_fn()
        generation_fn = self._render_generation_fn(example_names)

        return f'''"""
{model.capitalize()}-specific prompt templates for CausalLM model generation.

Auto-generated by the Prompt Harness from
{self.inp.source_path or "(LLM-generated implementation, no reference file)"}.
Source: {self.inp.source}

{model.capitalize()} architecture notes:
{self._render_notes_block()}
"""
from __future__ import annotations

import json
from typing import Dict, List, Optional

from knowledge.causallm_kb import (
    render_catalog,
    render_config_members,
    render_forbidden,
    render_hooks,
    render_name_contract,
    unregistered_types,
)

# Re-use common utilities from base prompts -- same as every other
# model-specific prompt module (prompts_qwen3_causallm.py, etc.)
from ..prompts_causallm import (
    GAP_MARKER_SPEC,
    SYSTEM_PROMPT,
    SELF_CHECK,
    _hard_constraints,
    correction_prompt,
    registration_prompt,
)

{header}
{worked_examples}
{constraints_fn}
{generation_fn}
'''

    def _render_notes_block(self) -> str:
        if not self.inp.architecture_notes:
            return "- (no architecture notes extracted)"
        return "\n".join(f"- {n}" for n in self.inp.architecture_notes)

    def _render_header(self) -> str:
        return f'''# ============================================================================
# {self.inp.model_name.upper()} generated by Prompt Harness -- verify before use
# ============================================================================'''

    def _render_worked_examples(self) -> str:
        model = self.inp.model_name.upper()
        blocks = []

        for key, pattern in self.inp.patterns.items():
            var_name = f"{model}_{key.upper()}_EXAMPLE"
            desc = pattern.description or f"{pattern.name} implementation"
            blocks.append(f'''
# ----------------------------------------------------------------------------
# {key.upper()} WORKED EXAMPLE (auto-extracted{" from reference" if self.inp.source == "reference" else " from LLM-generated draft"})
# ----------------------------------------------------------------------------
{var_name} = \'\'\'\\
{desc}

```cpp
{pattern.code}
```
\'\'\'
''')

        if not blocks:
            blocks.append(f'''
# NOTE: No worked examples were extracted. This model needs manual review --
# add a worked example here before relying on this prompt module.
{model}_PLACEHOLDER_EXAMPLE = "# TODO: no pattern extracted, add manually"
''')

        return "\n".join(blocks)

    def _render_constraints_fn(self) -> str:
        model = self.inp.model_name
        forbidden = self.inp.forbidden_patterns or [
            "Do NOT use HF dotted names like \"model.layers.0.self_attn.q_proj\"",
            "Do NOT invent layer types not present in the layer catalog",
        ]
        forbidden_lines = "\n".join(f"    * {f}" for f in forbidden)

        return f'''
# ============================================================================
# {model.upper()}-SPECIFIC HARD CONSTRAINTS (auto-generated -- REVIEW REQUIRED)
# ============================================================================
def {model}_hard_constraints(plan: Dict) -> str:
    """{model.capitalize()}-specific constraints on top of the common ones.

    NOTE: This was auto-generated by the Prompt Harness from
    {'a reference implementation' if self.inp.source == 'reference' else 'an LLM-generated draft'}.
    Review and tighten before trusting it for production generation.
    """
    common = _hard_constraints(plan)
    return f"""\\
{{common}}

M1. {model.upper()}-SPECIFIC PATTERNS (auto-extracted, verify)
{chr(10).join(f"    * {n}" for n in self.inp.architecture_notes) or "    * (none extracted -- fill in manually)"}

M2. {model.upper()} FORBIDDEN PATTERNS
{forbidden_lines}
"""
'''

    def _render_generation_fn(self, example_names: List[str]) -> str:
        model = self.inp.model_name
        examples_block = "\n\n".join(f"{{{name}}}" for name in example_names) if example_names else ""

        return f'''
# ============================================================================
# {model.upper()} GENERATION PROMPT (auto-generated -- REVIEW REQUIRED)
# ============================================================================
def {model}_generation_prompt(plan: Dict, skeleton_h: str, skeleton_cpp: str) -> str:
    """
    {model.capitalize()}-specific generation prompt.

    Auto-generated by the Prompt Harness. Uses worked examples extracted from
    {self.inp.source_path or "an LLM-generated draft implementation"}.
    """
    holes = plan.get("holes", [])
    hole_block = "\\n".join(
        f"  FILL:{{h['id']}}  {{h['hook']}}\\n"
        f"           goal   : {{h['goal']}}\\n"
        f"           layers : {{', '.join(h.get('layers', [])) or '(see plan)'}}"
        for h in holes
    ) or "  (none -- see skeleton markers)"

    hook_names = [h["hook"] for h in holes if h.get("hook")]

    return f"""\\
Fill in {{len(holes)}} marked hole(s) in the C++ skeleton below. Nothing else.

Model      : {{plan.get('model_id', '<unknown>')}}
Architecture: {{plan.get('architecture', '<unknown>')}}
Class      : {{plan.get('class_name', '<unknown>')}}
Base       : {{plan.get('base_class', 'causallm::CausalLM')}}

This is a {model.upper()}-family model (auto-generated prompt -- verify
architecture notes below match the target model before trusting output).

================================ 1. THE PLAN =================================
{{json.dumps(plan.get('resolved', plan), indent=2)}}

HOLES TO FILL:
{{hole_block}}

============================== 2. THE SKELETON ===============================
--- {{plan.get('file_stem', 'model')}}_causallm.h ---
```cpp
{{skeleton_h}}
```

--- {{plan.get('file_stem', 'model')}}_causallm.cpp ---
```cpp
{{skeleton_cpp}}
```

============================== 3. THE LAYER MENU =============================
{{render_catalog(only=plan.get('layer_types'))}}

=========================== 4. HARD CONSTRAINTS ==============================
{{{model}_hard_constraints(plan)}}

======================= 5. OVERRIDABLE HOOKS (exact) ========================
{{render_hooks(only=hook_names or None)}}

=========================== 6. WORKED EXAMPLES ===============================

{examples_block}

============================= 7. GAP MARKER =================================
{{GAP_MARKER_SPEC}}

============================= 8. SELF-CHECK =================================
{{SELF_CHECK}}

============================ 9. OUTPUT FORMAT ================================
Emit exactly two fenced blocks, in this order:

```cpp
// FILE: {{plan.get('file_stem', 'model')}}_causallm.h
<complete header>
```

```cpp
// FILE: {{plan.get('file_stem', 'model')}}_causallm.cpp
<complete source>
```
"""
'''

    def write(self) -> str:
        """Render and write the module to prompts_generated/. Returns the path."""
        os.makedirs(_GENERATED_DIR, exist_ok=True)
        filename = f"prompts_{self.inp.model_name}_causallm.py"
        out_path = os.path.join(_GENERATED_DIR, filename)

        content = self.render()
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write(content)

        return out_path
