"""C++ code generator for NNTrainer LayerPluggable custom layers.

Generates boilerplate C++ header and source files that implement the
NNTrainer LayerPluggable interface, ready for users to fill in their
custom layer logic (forwarding, calcDerivative, etc.).

Also generates meson.build entries for building the plugin as a shared library.

Usage:
    from plugin_codegen import generate_plugin_code

    files = generate_plugin_code(
        layer_type="custom_pow",
        class_name="PowLayer",
        properties={"exponent": "float"},
        has_weight=False,
        output_dir="./my_plugin/",
    )
"""

import os
import re


def _to_class_name(layer_type):
    """Convert layer_type string to CamelCase class name.

    "custom_pow" -> "CustomPowLayer"
    "my_norm" -> "MyNormLayer"
    """
    parts = layer_type.split("_")
    name = "".join(p.capitalize() for p in parts)
    if not name.endswith("Layer"):
        name += "Layer"
    return name


def _to_header_guard(class_name):
    """Convert class name to header guard macro.

    "CustomPowLayer" -> "__CUSTOM_POW_LAYER_H__"
    """
    # Insert underscores before uppercase letters
    s = re.sub(r'(?<!^)(?=[A-Z])', '_', class_name).upper()
    return f"__{s}_H__"


def generate_header(layer_type, class_name=None, properties=None,
                    has_weight=False, has_bias=False, namespace="custom"):
    """Generate C++ header file for a custom LayerPluggable layer.

    Args:
        layer_type: NNTrainer layer type string (e.g. "custom_pow").
        class_name: C++ class name. If None, derived from layer_type.
        properties: Dict of property_name -> c++ type (e.g. {"exponent": "float"}).
        has_weight: Whether the layer has trainable weights.
        has_bias: Whether the layer has a bias parameter.
        namespace: C++ namespace (default: "custom").

    Returns:
        Header file content as string.
    """
    if class_name is None:
        class_name = _to_class_name(layer_type)
    if properties is None:
        properties = {}

    guard = _to_header_guard(class_name)

    # Build member variables
    members = []
    for prop_name, prop_type in properties.items():
        default = _default_for_type(prop_type)
        members.append(f"  {prop_type} {prop_name}{{{default}}};")

    members_str = "\n".join(members) if members else "  // No custom properties"

    return f"""// SPDX-License-Identifier: Apache-2.0
/**
 * @file   {_to_filename(class_name)}.h
 * @brief  Custom NNTrainer layer: {layer_type}
 *
 * Auto-generated by TorchFXConverter plugin_codegen.
 * Implement forwarding() and calcDerivative() with your custom logic.
 */

#ifndef {guard}
#define {guard}

#include <layer_context.h>
#include <layer_devel.h>
#include <node_exporter.h>

namespace {namespace} {{

class {class_name} final : public nntrainer::Layer {{
public:
  {class_name}() : Layer() {{}}
  ~{class_name}() {{}}

  /**
   * @brief Set output dimensions and request weights.
   */
  void finalize(nntrainer::InitLayerContext &context) override;

  /**
   * @brief Forward propagation. Implement your custom logic here.
   */
  void forwarding(nntrainer::RunLayerContext &context, bool training) override;

  /**
   * @brief Backward propagation (gradient computation).
   */
  void calcDerivative(nntrainer::RunLayerContext &context) override;

  /**
   * @brief Whether this layer supports backpropagation.
   */
  bool supportBackwarding() const override {{ return {str(has_weight).lower()}; }}

  /**
   * @brief Export layer properties.
   */
  void exportTo(nntrainer::Exporter &exporter,
                const ml::train::ExportMethods &method) const override {{}}

  /**
   * @brief Return the layer type identifier.
   */
  const std::string getType() const override {{ return {class_name}::type; }}

  /**
   * @brief Parse layer properties from key=value strings.
   */
  void setProperty(const std::vector<std::string> &values) override;

  inline static const std::string type = "{layer_type}";

private:
{members_str}
}};

}} // namespace {namespace}

#endif /* {guard} */
"""


def generate_source(layer_type, class_name=None, properties=None,
                    has_weight=False, has_bias=False, namespace="custom"):
    """Generate C++ source file for a custom LayerPluggable layer.

    Args:
        layer_type: NNTrainer layer type string.
        class_name: C++ class name. If None, derived from layer_type.
        properties: Dict of property_name -> c++ type.
        has_weight: Whether the layer has trainable weights.
        has_bias: Whether the layer has a bias parameter.
        namespace: C++ namespace.

    Returns:
        Source file content as string.
    """
    if class_name is None:
        class_name = _to_class_name(layer_type)
    if properties is None:
        properties = {}

    filename = _to_filename(class_name)

    # Build setProperty parsing
    set_property_body = _generate_set_property(properties)

    # Build finalize body
    finalize_body = _generate_finalize(has_weight, has_bias)

    # Build forwarding body
    forwarding_body = _generate_forwarding(has_weight)

    # Build calcDerivative body
    calc_deriv_body = _generate_calc_derivative(has_weight)

    # Build pluggable section
    pluggable = _generate_pluggable(class_name, namespace)

    return f"""// SPDX-License-Identifier: Apache-2.0
/**
 * @file   {filename}.cpp
 * @brief  Custom NNTrainer layer: {layer_type}
 *
 * Auto-generated by TorchFXConverter plugin_codegen.
 * Implement forwarding() and calcDerivative() with your custom logic.
 */

#include "{filename}.h"

#include <iostream>
#include <regex>

namespace {namespace} {{

static constexpr size_t SINGLE_INOUT_IDX = 0;

// --------------------------------------------------------------------------
// Property parsing helper
// --------------------------------------------------------------------------

static std::pair<std::string, std::string>
parseKeyValue(const std::string &input) {{
  auto pos = input.find('=');
  if (pos == std::string::npos)
    throw std::invalid_argument("Invalid property: " + input);
  return {{input.substr(0, pos), input.substr(pos + 1)}};
}}

// --------------------------------------------------------------------------
// Layer interface implementation
// --------------------------------------------------------------------------

void {class_name}::setProperty(const std::vector<std::string> &values) {{
{set_property_body}
}}

void {class_name}::finalize(nntrainer::InitLayerContext &context) {{
{finalize_body}
}}

void {class_name}::forwarding(nntrainer::RunLayerContext &context,
                               bool training) {{
{forwarding_body}
}}

void {class_name}::calcDerivative(nntrainer::RunLayerContext &context) {{
{calc_deriv_body}
}}

{pluggable}
}} // namespace {namespace}
"""


def generate_meson_build(layer_type, class_name=None, namespace="custom"):
    """Generate meson.build snippet for building the plugin as shared library.

    Returns:
        meson.build content as string.
    """
    if class_name is None:
        class_name = _to_class_name(layer_type)

    filename = _to_filename(class_name)
    lib_name = f"{layer_type}_layer"

    return f"""# Build custom layer plugin: {layer_type}
# Add this to your meson.build or include it with subdir()

{lib_name}_src = files('{filename}.cpp')

shared_library('{lib_name}',
  sources: {lib_name}_src,
  dependencies: [nntrainer_dep],
  cpp_args: ['-DPLUGGABLE'],
  install: true,
  install_dir: nntrainer_libdir,
)
"""


def generate_plugin_code(layer_type, class_name=None, properties=None,
                         has_weight=False, has_bias=False,
                         namespace="custom", output_dir=None):
    """Generate complete plugin code (header + source + meson.build).

    Args:
        layer_type: NNTrainer layer type string.
        class_name: C++ class name (auto-derived if None).
        properties: Dict of property_name -> c++ type string.
        has_weight: Whether the layer has weights.
        has_bias: Whether the layer has bias.
        namespace: C++ namespace.
        output_dir: Directory to write files. If None, returns dict of content.

    Returns:
        Dict of filename -> content (if output_dir is None) or
        Dict of filename -> filepath (if output_dir is given).
    """
    if class_name is None:
        class_name = _to_class_name(layer_type)
    if properties is None:
        properties = {}

    filename = _to_filename(class_name)

    header = generate_header(layer_type, class_name, properties,
                             has_weight, has_bias, namespace)
    source = generate_source(layer_type, class_name, properties,
                             has_weight, has_bias, namespace)
    meson = generate_meson_build(layer_type, class_name, namespace)

    files = {
        f"{filename}.h": header,
        f"{filename}.cpp": source,
        "meson.build": meson,
    }

    if output_dir is None:
        return files

    os.makedirs(output_dir, exist_ok=True)
    result = {}
    for fname, content in files.items():
        fpath = os.path.join(output_dir, fname)
        with open(fpath, "w") as f:
            f.write(content)
        result[fname] = fpath

    return result


# ============================================================================
# Internal helpers
# ============================================================================

def _to_filename(class_name):
    """CamelCase -> snake_case filename (without extension)."""
    s = re.sub(r'(?<!^)(?=[A-Z])', '_', class_name).lower()
    return s


def _default_for_type(cpp_type):
    """Return default value string for a C++ type."""
    defaults = {
        "int": "0",
        "float": "1.0f",
        "double": "1.0",
        "bool": "false",
        "unsigned int": "0",
        "size_t": "0",
        "std::string": '""',
    }
    return defaults.get(cpp_type, "0")


def _parse_fn_for_type(cpp_type):
    """Return parsing expression for a C++ type from string."""
    parsers = {
        "int": "std::stoi(val)",
        "float": "std::stof(val)",
        "double": "std::stod(val)",
        "bool": "(val == \"true\" || val == \"1\")",
        "unsigned int": "static_cast<unsigned int>(std::stoul(val))",
        "size_t": "static_cast<size_t>(std::stoul(val))",
        "std::string": "val",
    }
    return parsers.get(cpp_type, f"/* TODO: parse {cpp_type} */")


def _generate_set_property(properties):
    """Generate setProperty body."""
    if not properties:
        return "  (void)values; // No custom properties"

    lines = ["  for (auto &v : values) {"]
    lines.append("    auto [key, val] = parseKeyValue(v);")

    first = True
    for prop_name, prop_type in properties.items():
        parse_expr = _parse_fn_for_type(prop_type)
        keyword = "if" if first else "} else if"
        lines.append(f'    {keyword} (key == "{prop_name}") {{')
        lines.append(f"      {prop_name} = {parse_expr};")
        first = False

    lines.append("    } else {")
    lines.append('      throw std::invalid_argument('
                 '"Unknown property: " + key);')
    lines.append("    }")
    lines.append("  }")
    return "\n".join(lines)


def _generate_finalize(has_weight, has_bias):
    """Generate finalize body."""
    lines = [
        "  // Set output dimensions (default: same as input)",
        "  context.setOutputDimensions(context.getInputDimensions());",
    ]
    if has_weight:
        lines.append("")
        lines.append("  // Request weights (customize dimensions as needed)")
        lines.append("  // auto &input_dim = context.getInputDimensions()[0];")
        lines.append("  // weight_idx = context.requestWeight(")
        lines.append('  //     input_dim, nntrainer::Initializer::XAVIER_UNIFORM,')
        lines.append('  //     nntrainer::WeightRegularizer::NONE, 0.0f,')
        lines.append('  //     context.getWeightDecay(), "weight", true);')
    return "\n".join(lines)


def _generate_forwarding(has_weight):
    """Generate forwarding body."""
    lines = [
        "  // TODO: Implement forward propagation",
        "  //",
        "  // Access input:  context.getInput(SINGLE_INOUT_IDX)",
        "  // Access output: context.getOutput(SINGLE_INOUT_IDX)",
    ]
    if has_weight:
        lines.append("  // Access weight: context.getWeight(weight_idx)")
    lines.extend([
        "  //",
        "  // Example (identity/passthrough):",
        "  context.getInput(SINGLE_INOUT_IDX)",
        "    .copy(context.getOutput(SINGLE_INOUT_IDX));",
    ])
    return "\n".join(lines)


def _generate_calc_derivative(has_weight):
    """Generate calcDerivative body."""
    lines = [
        "  // TODO: Implement backward propagation",
        "  //",
        "  // Access incoming gradient: context.getIncomingDerivative(SINGLE_INOUT_IDX)",
        "  // Set outgoing gradient:   context.getOutgoingDerivative(SINGLE_INOUT_IDX)",
        "  //",
        "  // Example (identity/passthrough):",
        "  context.getIncomingDerivative(SINGLE_INOUT_IDX)",
        "    .copy(context.getOutgoingDerivative(SINGLE_INOUT_IDX));",
    ]
    return "\n".join(lines)


def _generate_pluggable(class_name, namespace):
    """Generate PLUGGABLE extern C section."""
    lower = _to_filename(class_name)
    return f"""// --------------------------------------------------------------------------
// Plugin entry point (for dynamic loading as .so)
// --------------------------------------------------------------------------

#ifdef PLUGGABLE

nntrainer::Layer *create_{lower}() {{
  return new {class_name}();
}}

void destroy_{lower}(nntrainer::Layer *layer) {{
  delete layer;
}}

extern "C" {{
nntrainer::LayerPluggable ml_train_layer_pluggable{{
  create_{lower},
  destroy_{lower}
}};
}}

#endif
"""
