"""
Qwen3-MoE family variant generator.

The hand-written reference (Applications/CausalLM/models/qwen3_moe/,
qwen3_slim_moe/, qwen3_cached_slim_moe/) shows these models don't need
their own attention/decoder-loop/base-config generation at all -- each
one is a thin C++ subclass of Qwen3CausalLM that overrides exactly two
things: setupParameters() (reads 3 extra MoE config fields) and
createMlp() (swaps the whole gate/up/down decomposition for a single
custom expert-routing layer already implemented in nntrainer). This
generator mirrors that ground-truthed shape (see qwen3_moe_causallm.h/
.cpp) instead of trying to derive expert routing from a traced graph --
there is no graph IR concept for MoE routing (see
converters/cpp_generator.py's module docstring), and none is needed here
since the delta is this small and this uniform across all three flavors.
"""
from ..cpp_generator import ComponentFiles

# HF architectures[0] string -> which flavor's custom expert-routing
# layer to target. All three read identical config fields and only
# differ in which pre-built nntrainer layer implements the routing (see
# Applications/CausalLM/models/qwen3_*moe*/qwen_moe_layer*.{h,cpp}).
FLAVORS = {
    "standard": {
        "class_name": "Qwen3MoECausalLM",
        "file_slug": "qwen3_moe_causallm",
        "moe_layer_type": "qwen_moe",
        "moe_registered_class": "MoELayer",
        "moe_layer_header": "qwen_moe_layer.h",
    },
    "slim": {
        "class_name": "Qwen3SlimMoECausalLM",
        "file_slug": "qwen3_slim_moe_causallm",
        "moe_layer_type": "moe_slim",
        "moe_registered_class": "SlimMoELayer",
        "moe_layer_header": "qwen_moe_layer_fsu.h",
    },
    "cached_slim": {
        "class_name": "Qwen3CachedSlimMoECausalLM",
        "file_slug": "qwen3_cached_slim_moe_causallm",
        "moe_layer_type": "moe_cached_slim",
        "moe_registered_class": "CachedSlimMoELayer",
        "moe_layer_header": "qwen_moe_layer_cached.h",
    },
}

_BASE_CLASS = "Qwen3CausalLM"
_BASE_HEADER = "qwen3_causallm.h"

# There is exactly one real upstream HF architecture string for Qwen3-MoE
# models (e.g. Qwen/Qwen3-30B-A3B) -- "slim"/"cached_slim" are
# nntrainer-internal deployment choices (which pre-built expert-routing
# layer to target), never something HF's AutoConfig reports. Select
# between them via state["qwen_moe_variant"] (default "standard"),
# not architecture detection.
SUPPORTED_ARCHITECTURES = {"Qwen3MoeForCausalLM"}


def detect(architecture: str, hf_config: dict) -> bool:
    return architecture in SUPPORTED_ARCHITECTURES


def generate(architecture: str, hf_config: dict, flavor: str = "standard") -> ComponentFiles:
    spec = FLAVORS.get(flavor, FLAVORS["standard"])
    class_name = spec["class_name"]
    guard_name = f"__{spec['file_slug'].upper()}_H__"
    header_filename = f"{spec['file_slug']}.h"
    source_filename = f"{spec['file_slug']}.cpp"

    header = f"""/**
 * AUTO-GENERATED FILE.
 *
 * Generated by AI Compiler Workbench -- {class_name} ({flavor} MoE variant).
 * A delta on top of {_BASE_CLASS}: reuses its attention, decoder loop,
 * and base config parsing unchanged; only overrides createMlp() (expert
 * routing) and setupParameters() (3 extra MoE config fields).
 * Do not edit manually -- regenerate instead.
 */

#ifndef {guard_name}
#define {guard_name} {guard_name}

#include <causal_lm.h>
#include <{_BASE_HEADER}>

namespace causallm {{

/**
 * @brief {class_name} class
 * @note  Inherits {_BASE_CLASS}; only the MLP (expert routing) differs.
 */
class {class_name} : public {_BASE_CLASS} {{

public:
  static constexpr const char *architectures = "{architecture}";

  {class_name}(json &cfg, json &generation_cfg, json &nntr_cfg) :
    Transformer(cfg, generation_cfg, nntr_cfg, ModelType::CAUSALLM),
    {_BASE_CLASS}(cfg, generation_cfg, nntr_cfg) {{
    setupParameters(cfg, generation_cfg, nntr_cfg);
  }}

  virtual ~{class_name}() = default;

  Tensor createMlp(const int layer_id, int dim, int hidden_dim,
                   Tensor input) override;

  void setupParameters(json &cfg, json &generation_cfg,
                       json &nntr_cfg) override;

  void registerCustomLayers() override;

private:
  unsigned int NUM_EXPERTS;
  unsigned int NUM_EXPERTS_PER_TOK;
}};
}}; // namespace causallm

#endif /* {guard_name} */
"""

    source = f"""/**
 * AUTO-GENERATED FILE. See {header_filename}.
 * Do not edit manually -- regenerate instead.
 */
#include <llm_util.hpp>
#include <model.h>
#include <{header_filename}>

#include <app_context.h>
#include <engine.h>
#include <{spec['moe_layer_header']}>

namespace causallm {{

void {class_name}::setupParameters(json &cfg, json &generation_cfg,
                                   json &nntr_cfg) {{
  {_BASE_CLASS}::setupParameters(cfg, generation_cfg, nntr_cfg);

  try {{
    NUM_EXPERTS = cfg["num_experts"];
    NUM_EXPERTS_PER_TOK = cfg["num_experts_per_tok"];
    INTERMEDIATE_SIZE = cfg["moe_intermediate_size"];
  }} catch (const std::exception &e) {{
    throw std::runtime_error("{class_name}: num_experts and "
                             "num_experts_per_tok are not specified in the config file");
  }}
}}

Tensor {class_name}::createMlp(const int layer_id, int dim, int hidden_dim,
                               Tensor input) {{

  LayerHandle moe(createLayer(
    "{spec['moe_layer_type']}",
    {{withKey("name", "layer" + std::to_string(layer_id) + "_ffn_down"),
     withKey("unit", hidden_dim), withKey("num_experts", NUM_EXPERTS),
     withKey("num_experts_per_token", NUM_EXPERTS_PER_TOK),
     withKey("moe_activation", "swish")}}));
  return moe(input);
}}

void {class_name}::registerCustomLayers() {{

  {_BASE_CLASS}::registerCustomLayers();
  auto &ct_engine = nntrainer::Engine::Global();
  auto app_context =
    static_cast<nntrainer::AppContext *>(ct_engine.getRegisteredContext("cpu"));

  try {{
    app_context->registerFactory(nntrainer::createLayer<causallm::{spec['moe_registered_class']}>);
  }} catch (std::invalid_argument &e) {{
    std::cerr << "failed to register factory, reason: " << e.what()
              << std::endl;
  }}
}}

}} // namespace causallm
"""

    return ComponentFiles(
        header=header,
        source=source,
        header_filename=header_filename,
        source_filename=source_filename,
        transformer_class=class_name,
        causal_lm_class=class_name,
        architecture=architecture,
    )
