"""C++ code emitter package for NNTrainer TorchFX converter.

Generates class-based C++ header (.h) and source (.cpp) files that construct
NNTrainer models. The emitter is split into focused sub-modules:
  - helpers.py          : C++ code gen utilities and naming
  - header.py           : Header file generation
  - source_construct.py : constructModel() generation
  - source_block.py     : createTransformerBlock() generation
  - source_attention.py : createAttention() generation
  - source_ffn.py       : createMlp() generation
  - source_custom.py    : registerCustomLayers() generation
"""

import sys
import os

from emitter_base import BaseEmitter
from .helpers import (
    _q, _cpp_layer, _cpp_tensor_layer, _with_key,
    _class_name, _file_basename, _header_guard,
    _sanitize_model_name, get_output_filenames,
    get_file_base, get_norm_type,
)
from .header import emit_flat_header, emit_structured_header
from .source_construct import emit_flat_source, emit_construct_model
from .source_block import emit_block_method
from .source_attention import emit_attention_method
from .source_ffn import emit_ffn_method
from .source_custom import (
    collect_custom_layer_classes, emit_register_custom_layers,
    emit_custom_layer_includes, emit_initialize,
    emit_allocate_kv_cache, CUSTOM_LAYER_CLASS,
)
from .legacy_emitter import emit_legacy_construct_model

# Re-export for backward compatibility
sys.modules.setdefault(
    "emitter_cpp.helpers",
    sys.modules[__name__ + ".helpers"]
)


class CppEmitter(BaseEmitter):
    """Generates class-based C++ header and source code from converter output.

    Orchestrates the sub-modules to produce the complete C++ output.
    """

    def __init__(self, layers, structure, model_name=None,
                 inherit_transformer=False):
        super().__init__(layers, structure, model_name=model_name)
        self._inherit_transformer = inherit_transformer

    def emit(self):
        """Generate combined C++ code (header + source)."""
        return self.emit_header() + "\n" + self.emit_source()

    # ----- Header -----

    def emit_header(self):
        """Generate C++ header file (.h) content."""
        if self._is_flat_model():
            return emit_flat_header(self.structure, self._model_name)
        return emit_structured_header(
            self.structure, self._blocks_info(), self._model_name,
            inherit_transformer=self._inherit_transformer)

    # ----- Source -----

    def emit_source(self):
        """Generate C++ source file (.cpp) content."""
        if self._is_flat_model():
            return emit_flat_source(
                self.layers, self.structure, self._model_name)
        if self._inherit_transformer:
            return self._emit_inherit_source()
        return self._emit_structured_source()

    def _emit_structured_source(self):
        """Generate source for transformer models (block-based structure)."""
        s = self.structure
        cname = _class_name(s.model_type, s.arch_type)
        block_type = ("DecoderBlock" if s.arch_type == "decoder_only"
                      else "Block")
        header_file = get_file_base(s, self._model_name) + ".h"

        # Collect custom classes early (needed for includes)
        norm_type = get_norm_type(s.model_type)
        attn_block = self._get_attn_block()
        custom_classes = collect_custom_layer_classes(
            s, norm_type, attn_block)

        L = []
        L.append(f"// Auto-generated by TorchFX-to-NNTrainer converter")
        L.append(f"// Model: {s.model_type} ({s.arch_type})")
        L.append(f"")
        L.append(f'#include "{header_file}"')
        L.append(f"#include <model.h>")
        L.append(f"#include <tensor_api.h>")
        L.append(f"#include <app_context.h>")
        L.append(f"#include <engine.h>")
        L.append(f"")
        includes = emit_custom_layer_includes(custom_classes)
        if includes:
            L.append(includes)
            L.append(f"")
        L.append(f"using ml::train::createLayer;")
        L.append(f"using ml::train::Tensor;")
        L.append(f"using LayerHandle = ml::train::LayerHandle;")
        L.append(f"")

        # withKey helper templates
        L.append("template <typename T>")
        L.append('static std::string withKey(const std::string &key, T val) {')
        L.append('  return key + "=" + std::to_string(val);')
        L.append("}")
        L.append("")
        L.append("template <>")
        L.append('std::string withKey(const std::string &key, '
                 'std::string val) {')
        L.append('  return key + "=" + val;')
        L.append("}")
        L.append("")
        L.append("template <>")
        L.append('std::string withKey(const std::string &key, '
                 'const char *val) {')
        L.append('  return key + "=" + std::string(val);')
        L.append("}")
        L.append("")

        # Default constructor
        L.append(f"{cname}::{cname}() = default;")
        L.append("")

        # constructModel
        if s.arch_type == "encoder_decoder":
            bt = None
        else:
            bt = block_type
        blocks_info = {
            "op_type_list": [b.operator_type for b in s.blocks],
        }
        L.append(emit_construct_model(s, bt, self._is_hybrid_model(),
                                      blocks_info))

        # Block methods
        if s.arch_type == "encoder_decoder":
            self._emit_enc_dec_blocks(L, cname, s)
        elif s.blocks:
            self._emit_standard_blocks(L, cname, block_type, s)

        # registerCustomLayers (custom_classes already collected above)
        L.append(emit_register_custom_layers(cname, custom_classes))

        # allocateKVCache (external mode)
        if s.external_kv_cache:
            L.append(emit_allocate_kv_cache(cname))

        # initialize()
        L.append(emit_initialize(cname,
                                 external_kv_cache=s.external_kv_cache))

        return "\n".join(L)

    def _emit_enc_dec_blocks(self, L, cname, s):
        """Emit encoder/decoder block methods."""
        enc_blocks = s.encoder_blocks
        dec_blocks = s.decoder_blocks
        enc_b0 = enc_blocks[0] if enc_blocks else None
        dec_b0 = dec_blocks[0] if dec_blocks else None

        if enc_b0:
            L.append(emit_block_method(
                cname, "EncoderBlock", enc_b0, s, is_encoder=True))
        if dec_b0:
            L.append(emit_block_method(
                cname, "DecoderBlock", dec_b0, s, is_encoder=False))

        representative = enc_b0 or dec_b0
        if representative and representative.attention:
            L.append(emit_attention_method(
                cname, representative, arch_type=s.arch_type,
                external_kv_cache=s.external_kv_cache))
        if representative and representative.ffn:
            L.append(emit_ffn_method(cname, representative))

    def _emit_standard_blocks(self, L, cname, block_type, s):
        """Emit standard block methods."""
        op_types = self._get_operator_types()
        for op_type in op_types:
            rep_block = self._get_block_by_operator(op_type)
            L.append(emit_block_method(cname, block_type, rep_block, s))

        attn_block = self._get_attn_block()
        if attn_block:
            L.append(emit_attention_method(
                cname, attn_block, arch_type=s.arch_type,
                external_kv_cache=s.external_kv_cache))

        representative = next((b for b in s.blocks if b.ffn), None)
        if representative:
            L.append(emit_ffn_method(cname, representative))

    def _emit_inherit_source(self):
        """Generate source for Transformer-inheriting models.

        Only emits overridden methods (createAttention, registerCustomLayers)
        plus a test factory method.
        """
        from .source_inherit import emit_inherit_source
        s = self.structure
        attn_block = self._get_attn_block()
        norm_type = get_norm_type(s.model_type)
        custom_classes = collect_custom_layer_classes(
            s, norm_type, attn_block)
        return emit_inherit_source(
            s, attn_block, custom_classes, self._model_name,
            layers=self.layers)

    # ----- Internal helpers -----

    def _is_flat_model(self):
        return not self.structure.blocks

    def _get_operator_types(self):
        types = set()
        for b in self.structure.blocks:
            types.add(b.operator_type)
        return sorted(types)

    def _is_hybrid_model(self):
        return len(self._get_operator_types()) > 1

    def _get_attn_block(self):
        for b in self.structure.blocks:
            if b.attention is not None:
                return b
        return None

    def _get_block_by_operator(self, operator_type):
        for b in self.structure.blocks:
            if b.operator_type == operator_type:
                return b
        return None

    def _blocks_info(self):
        """Build blocks_info dict for header generation."""
        return {
            "attn_block": self._get_attn_block(),
            "is_hybrid": self._is_hybrid_model(),
            "op_types": self._get_operator_types(),
        }

    # Backward compatibility attributes
    _CUSTOM_LAYER_CLASS = CUSTOM_LAYER_CLASS

    def _get_norm_type(self):
        return get_norm_type(self.structure.model_type)

    def _file_base(self):
        return get_file_base(self.structure, self._model_name)

    def _collect_custom_layer_classes(self):
        norm_type = get_norm_type(self.structure.model_type)
        attn_block = self._get_attn_block()
        return collect_custom_layer_classes(
            self.structure, norm_type, attn_block)


# =============================================================================
# Convenience functions (backward compatible)
# =============================================================================

def emit_cpp(layers, structure, model_name=None, inherit_transformer=False):
    """Generate combined C++ code (header + source)."""
    return CppEmitter(layers, structure, model_name=model_name,
                      inherit_transformer=inherit_transformer).emit()


def emit_cpp_header(layers, structure, model_name=None,
                    inherit_transformer=False):
    """Generate C++ header file (.h) content."""
    return CppEmitter(layers, structure, model_name=model_name,
                      inherit_transformer=inherit_transformer).emit_header()


def emit_cpp_source(layers, structure, model_name=None,
                    inherit_transformer=False):
    """Generate C++ source file (.cpp) content."""
    return CppEmitter(layers, structure, model_name=model_name,
                      inherit_transformer=inherit_transformer).emit_source()


def emit_legacy_cpp_source(layers, structure, model_name=None):
    """Generate C++ source file (.cpp) content using the legacy addLayer pattern."""
    from .source_custom import (
        collect_custom_layer_classes, emit_register_custom_layers,
        emit_custom_layer_includes, emit_initialize,
        emit_allocate_kv_cache,
    )
    
    s = structure
    cname = _class_name(s.model_type, s.arch_type)
    header_file = get_file_base(s, model_name) + ".h"
    norm_type = get_norm_type(s.model_type)
    attn_block = None
    for b in (s.blocks or []):
        if b.attention is not None:
            attn_block = b
            break
    
    # Collect custom classes
    custom_classes = collect_custom_layer_classes(s, norm_type, attn_block)
    
    L = []
    L.append(f"// Auto-generated by TorchFX-to-NNTrainer converter")
    L.append(f"// Model: {s.model_type} ({s.arch_type})")
    L.append(f"")
    L.append(f'#include "{header_file}"')
    L.append(f"#include <app_context.h>")
    L.append(f"#include <engine.h>")
    L.append(f"")
    
    includes = emit_custom_layer_includes(custom_classes)
    if includes:
        L.append(includes)
        L.append(f"")
    
    L.append(f"using ml::train::createLayer;")
    L.append(f"")
    
    # withKey helper templates
    L.append("template <typename T>")
    L.append('static std::string withKey(const std::string &key, T val) {')
    L.append('  return key + "=" + std::to_string(val);')
    L.append("}")
    L.append("")
    L.append("template <>")
    L.append('std::string withKey(const std::string &key, '
             'std::string val) {')
    L.append('  return key + "=" + val;')
    L.append("}")
    L.append("")
    L.append("template <>")
    L.append('std::string withKey(const std::string &key, '
             'const char *val) {')
    L.append('  return key + "=" + std::string(val);')
    L.append("}")
    L.append("")
    
    # Default constructor
    L.append(f"{cname}::{cname}() = default;")
    L.append("")
    
    # constructModel using legacy pattern
    if s.arch_type == "encoder_decoder":
        bt = None
    else:
        bt = "DecoderBlock" if s.arch_type == "decoder_only" else "Block"
    
    blocks_info = {
        "op_type_list": [b.operator_type for b in s.blocks or []],
    }
    
    L.append(emit_legacy_construct_model(s, bt, len(blocks_info["op_type_list"]) > 1, blocks_info))
    
    # For legacy emitter, we need to generate proper block methods that return std::vector<LayerHandle>
    # and create layers using the addLayer pattern.
    
    # Block methods - generate proper implementations that return std::vector<LayerHandle>
    if s.blocks:
        # Generate createTransformerDecoderBlock method
        L.append(f"std::vector<LayerHandle>")
        L.append(f"{cname}::createTransformerDecoderBlock(const int layer_id, std::string input_name) {{")
        L.append(f"  std::vector<LayerHandle> layers;")
        L.append(f"")
        L.append(f"  // Pre-attention normalization")
        L.append(f"  layers.push_back(createLayer(\"rms_norm\", {{")
        L.append(f"    withKey(\"name\", \"layer\" + std::to_string(layer_id) + \"_attention_norm\"),")
        L.append(f"    withKey(\"input_layers\", input_name),")
        L.append(f"    withKey(\"epsilon\", std::to_string(NORM_EPS)),")
        L.append(f"    withKey(\"packed\", \"false\")")
        L.append(f"  }}));")
        L.append(f"")
        L.append(f"  // Self attention")
        L.append(f"  auto att_layer = createAttention(layer_id, INIT_SEQ_LEN, NUM_HEADS, HEAD_DIM,")
        L.append(f"    \"layer\" + std::to_string(layer_id) + \"_attention_norm\",")
        L.append(f"    \"layer\" + std::to_string(layer_id) + \"_attention_norm\",")
        L.append(f"    \"layer\" + std::to_string(layer_id) + \"_attention_norm\");")
        L.append(f"  layers.insert(layers.end(), att_layer.begin(), att_layer.end());")
        L.append(f"")
        L.append(f"  // Attention residual connection (addition)")
        L.append(f"  layers.push_back(createLayer(\"addition\", {{")
        L.append(f"    withKey(\"name\", \"layer\" + std::to_string(layer_id) + \"_decoder_add\"),")
        L.append(f"    withKey(\"input_layers\", input_name + \",layer\" + std::to_string(layer_id) + \"_attention_out\")")
        L.append(f"  }}));")
        L.append(f"")
        L.append(f"  // Pre-FFN normalization")
        L.append(f"  layers.push_back(createLayer(\"rms_norm\", {{")
        L.append(f"    withKey(\"name\", \"layer\" + std::to_string(layer_id) + \"_ffn_norm\"),")
        L.append(f"    withKey(\"input_layers\", \"layer\" + std::to_string(layer_id) + \"_decoder_add\"),")
        L.append(f"    withKey(\"epsilon\", std::to_string(NORM_EPS)),")
        L.append(f"    withKey(\"packed\", \"false\")")
        L.append(f"  }}));")
        L.append(f"")
        L.append(f"  // Feed forward")
        L.append(f"  auto ffn_layer = createMlp(layer_id, DIM, INTERMEDIATE_SIZE,")
        L.append(f"    \"layer\" + std::to_string(layer_id) + \"_ffn_norm\");")
        L.append(f"  layers.insert(layers.end(), ffn_layer.begin(), ffn_layer.end());")
        L.append(f"")
        L.append(f"  // FFN residual connection (addition)")
        L.append(f"  layers.push_back(createLayer(\"addition\", {{")
        L.append(f"    withKey(\"name\", \"layer\" + std::to_string(layer_id) + \"_decoder_output\"),")
        L.append(f"    withKey(\"input_layers\", \"layer\" + std::to_string(layer_id) + \"_decoder_add,layer\" + ")
        L.append(f"      std::to_string(layer_id) + \"_ffn_down\")")
        L.append(f"  }}));")
        L.append(f"")
        L.append(f"  return layers;")
        L.append(f"}}")
        L.append(f"")
        
        # Generate createAttention method
        L.append(f"std::vector<LayerHandle>")
        L.append(f"{cname}::createAttention(const int layer_id, int seq_len, int n_heads,")
        L.append(f"                           int head_dim, std::string query_name,")
        L.append(f"                           std::string key_name, std::string value_name) {{")
        L.append(f"  std::vector<LayerHandle> layers;")
        L.append(f"")
        L.append(f"  auto V_name = \"layer\" + std::to_string(layer_id) + \"_wv\";")
        L.append(f"  auto K_name = \"layer\" + std::to_string(layer_id) + \"_wk\";")
        L.append(f"  auto Q_name = \"layer\" + std::to_string(layer_id) + \"_wq\";")
        L.append(f"  auto K_norm_name = \"layer\" + std::to_string(layer_id) + \"_k_norm\";")
        L.append(f"  auto Q_norm_name = \"layer\" + std::to_string(layer_id) + \"_q_norm\";")
        L.append(f"  auto A_name = \"layer\" + std::to_string(layer_id) + \"_attention\";")
        L.append(f"  auto O_name = \"layer\" + std::to_string(layer_id) + \"_attention_out\";")
        L.append(f"")
        L.append(f"  // Q projection")
        L.append(f"  layers.push_back(createLayer(\"fully_connected\", {{")
        L.append(f"    withKey(\"name\", Q_name),")
        L.append(f"    withKey(\"unit\", head_dim * n_heads),")
        L.append(f"    withKey(\"disable_bias\", \"true\"),")
        L.append(f"    withKey(\"input_layers\", query_name),")
        L.append(f"    withKey(\"weight_initializer\", \"ones\")")
        L.append(f"  }}));")
        L.append(f"")
        L.append(f"  // Q norm (reshaped RMS norm) - for Qwen3 style attention")
        L.append(f"  layers.push_back(createLayer(\"reshaped_rms_norm\", {{")
        L.append(f"    withKey(\"name\", Q_norm_name),")
        L.append(f"    withKey(\"input_layers\", Q_name),")
        L.append(f"    withKey(\"packed\", \"false\"),")
        L.append(f"    withKey(\"epsilon\", std::to_string(NORM_EPS)),")
        L.append(f"    withKey(\"feature_size\", head_dim)")
        L.append(f"  }}));")
        L.append(f"")
        L.append(f"  // K projection")
        L.append(f"  layers.push_back(createLayer(\"fully_connected\", {{")
        L.append(f"    withKey(\"name\", K_name),")
        L.append(f"    withKey(\"unit\", head_dim * n_heads / GQA_SIZE),")
        L.append(f"    withKey(\"disable_bias\", \"true\"),")
        L.append(f"    withKey(\"input_layers\", key_name),")
        L.append(f"    withKey(\"weight_initializer\", \"ones\")")
        L.append(f"  }}));")
        L.append(f"")
        L.append(f"  // K norm (reshaped RMS norm) - for Qwen3 style attention")
        L.append(f"  layers.push_back(createLayer(\"reshaped_rms_norm\", {{")
        L.append(f"    withKey(\"name\", K_norm_name),")
        L.append(f"    withKey(\"input_layers\", K_name),")
        L.append(f"    withKey(\"packed\", \"false\"),")
        L.append(f"    withKey(\"epsilon\", std::to_string(NORM_EPS)),")
        L.append(f"    withKey(\"feature_size\", head_dim)")
        L.append(f"  }}));")
        L.append(f"")
        L.append(f"  // V projection")
        L.append(f"  layers.push_back(createLayer(\"fully_connected\", {{")
        L.append(f"    withKey(\"name\", V_name),")
        L.append(f"    withKey(\"unit\", head_dim * n_heads / GQA_SIZE),")
        L.append(f"    withKey(\"disable_bias\", \"true\"),")
        L.append(f"    withKey(\"input_layers\", value_name),")
        L.append(f"    withKey(\"weight_initializer\", \"ones\")")
        L.append(f"  }}));")
        L.append(f"")
        L.append(f"  // Attention core layer")
        L.append(f"  layers.push_back(createLayer(\"mha_core\", {{")
        L.append(f"    withKey(\"name\", A_name),")
        L.append(f"    withKey(\"num_heads\", n_heads),")
        L.append(f"    withKey(\"num_heads_kv\", n_heads / GQA_SIZE),")
        L.append(f"    withKey(\"max_timestep\", std::to_string(INIT_SEQ_LEN + NUM_TO_GENERATE)),")
        L.append(f"    withKey(\"rope_theta\", ROPE_THETA),")
        L.append(f"    withKey(\"max_position_embeddings\", MAX_POSITION_EMBEDDINGS),")
        L.append(f"    withKey(\"max_new_tokens\", std::to_string(NUM_TO_GENERATE)),")
        L.append(f"    withKey(\"input_layers\", Q_norm_name + std::string(\",\") + K_norm_name + std::string(\",\") + V_name)")
        L.append(f"  }}));")
        L.append(f"")
        L.append(f"  // O projection")
        L.append(f"  layers.push_back(createLayer(\"fully_connected\", {{")
        L.append(f"    withKey(\"name\", O_name),")
        L.append(f"    withKey(\"unit\", DIM),")
        L.append(f"    withKey(\"disable_bias\", \"true\"),")
        L.append(f"    withKey(\"input_layers\", A_name),")
        L.append(f"    withKey(\"weight_initializer\", \"ones\")")
        L.append(f"  }}));")
        L.append(f"")
        L.append(f"  return layers;")
        L.append(f"}}")
        L.append(f"")
        
        # Generate createMlp method
        L.append(f"std::vector<LayerHandle>")
        L.append(f"{cname}::createMlp(const int layer_id, int dim, int hidden_dim,")
        L.append(f"                     std::string input_name) {{")
        L.append(f"  std::vector<LayerHandle> layers;")
        L.append(f"")
        L.append(f"  // FFN up projection")
        L.append(f"  layers.push_back(createLayer(\"fully_connected\", {{")
        L.append(f"    withKey(\"name\", \"layer\" + std::to_string(layer_id) + \"_ffn_up\"),")
        L.append(f"    withKey(\"unit\", hidden_dim),")
        L.append(f"    withKey(\"disable_bias\", \"true\"),")
        L.append(f"    withKey(\"input_layers\", input_name),")
        L.append(f"    withKey(\"weight_initializer\", \"ones\")")
        L.append(f"  }}));")
        L.append(f"")
        L.append(f"  // FFN gate projection")
        L.append(f"  layers.push_back(createLayer(\"fully_connected\", {{")
        L.append(f"    withKey(\"name\", \"layer\" + std::to_string(layer_id) + \"_ffn_gate\"),")
        L.append(f"    withKey(\"unit\", hidden_dim),")
        L.append(f"    withKey(\"disable_bias\", \"true\"),")
        L.append(f"    withKey(\"input_layers\", input_name),")
        L.append(f"    withKey(\"weight_initializer\", \"ones\")")
        L.append(f"  }}));")
        L.append(f"")
        L.append(f"  // SwiGLU activation")
        L.append(f"  layers.push_back(createLayer(\"swiglu\", {{")
        L.append(f"    withKey(\"name\", \"layer\" + std::to_string(layer_id) + \"_ffn_swiglu\"),")
        L.append(f"    withKey(\"input_layers\", \"layer\" + std::to_string(layer_id) + \"_ffn_gate,\" +")
        L.append(f"      \"layer\" + std::to_string(layer_id) + \"_ffn_up\")")
        L.append(f"  }}));")
        L.append(f"")
        L.append(f"  // FFN down projection")
        L.append(f"  layers.push_back(createLayer(\"fully_connected\", {{")
        L.append(f"    withKey(\"name\", \"layer\" + std::to_string(layer_id) + \"_ffn_down\"),")
        L.append(f"    withKey(\"unit\", dim),")
        L.append(f"    withKey(\"disable_bias\", \"true\"),")
        L.append(f"    withKey(\"input_layers\", \"layer\" + std::to_string(layer_id) + \"_ffn_swiglu\"),")
        L.append(f"    withKey(\"weight_initializer\", \"ones\")")
        L.append(f"  }}));")
        L.append(f"")
        L.append(f"  return layers;")
        L.append(f"}}")
        L.append(f"")
    
    # registerCustomLayers (same as current implementation)
    L.append(emit_register_custom_layers(cname, custom_classes))
    
    # allocateKVCache (same as current implementation)
    if getattr(s, 'external_kv_cache', False):
        L.append(emit_allocate_kv_cache(cname))
    
    # initialize (same as current implementation)
    L.append(emit_initialize(cname, external_kv_cache=getattr(s, 'external_kv_cache', False)))
    
    return "\n".join(L)
