"""C++ header file (.h) generation for NNTrainer models."""

from .helpers import _class_name, get_file_base


def emit_flat_header(structure, model_name=None):
    """Generate header for non-transformer models (flat layer list)."""
    s = structure
    cname = _class_name(s.model_type, s.arch_type)
    base = get_file_base(s, model_name)
    guard = f"__{base.upper()}_H__"

    L = []
    L.append(f"// Auto-generated by TorchFX-to-NNTrainer converter")
    L.append(f"// Model: {s.model_type}")
    L.append(f"")
    L.append(f"#ifndef {guard}")
    L.append(f"#define {guard}")
    L.append(f"")
    L.append(f"#include <layer.h>")
    L.append(f"#include <model.h>")
    L.append(f"#include <tensor_api.h>")
    L.append(f"")
    L.append(f"using LayerHandle = ml::train::LayerHandle;")
    L.append(f"using Tensor = ml::train::Tensor;")
    L.append(f"using ModelHandle = std::unique_ptr<ml::train::Model>;")
    L.append(f"")
    L.append(f"/**")
    L.append(f" * @brief {cname} Class")
    L.append(f" * @note Auto-generated from {s.model_type} model")
    L.append(f" */")
    L.append(f"class {cname} {{")
    L.append(f"")
    L.append(f"public:")
    L.append(f"  {cname}();")
    L.append(f"  virtual ~{cname}() = default;")
    L.append(f"")
    L.append(f"  /**")
    L.append(f"   * @brief Construct the model graph")
    L.append(f"   */")
    L.append(f"  virtual void constructModel();")
    L.append(f"")
    L.append(f"  /**")
    L.append(f"   * @brief Initialize the model (register layers, construct, compile)")
    L.append(f"   */")
    L.append(f"  virtual void initialize();")
    L.append(f"")
    L.append(f"  /**")
    L.append(f"   * @brief Get the underlying model handle")
    L.append(f"   */")
    L.append(f"  ModelHandle &getModel() {{ return model; }}")
    L.append(f"")
    L.append(f"protected:")
    L.append(f"  virtual void registerCustomLayers();")
    L.append(f"  ModelHandle model;")
    L.append(f"}};")
    L.append(f"")
    L.append(f"#endif // {guard}")
    L.append(f"")
    return "\n".join(L)


def emit_structured_header(structure, blocks_info, model_name=None,
                           inherit_transformer=False):
    """Generate header for transformer models (block-based structure).

    Args:
        structure: ModelStructure
        blocks_info: dict with keys:
            - attn_block: first block with attention (or None)
            - is_hybrid: bool
            - op_types: sorted list of unique operator types
        model_name: optional model name override
        inherit_transformer: if True, generate class inheriting from
            CausalLM/Transformer base class in causallm namespace
    """
    if inherit_transformer:
        return _emit_inherit_header(structure, blocks_info, model_name)
    return _emit_standalone_header(structure, blocks_info, model_name)


def _emit_inherit_header(structure, blocks_info, model_name):
    """Generate header that inherits from CausalLM/Transformer base class."""
    s = structure
    cname = _class_name(s.model_type, s.arch_type)
    base = get_file_base(s, model_name)
    guard = f"__{base.upper()}_H__"

    attn_block = blocks_info["attn_block"]
    has_qk_norm = attn_block and attn_block.attention.has_qk_norm

    # Determine base class
    has_lm_head = bool(s.lm_head)
    if has_lm_head and s.arch_type == "decoder_only":
        base_class = "CausalLM"
        base_header = "causal_lm.h"
    else:
        base_class = "Transformer"
        base_header = "transformer.h"

    # Determine if we need a separate Transformer variant class (like Qwen3Transformer)
    need_variant = has_qk_norm  # Model has attention differences from base

    L = []
    L.append(f"// Auto-generated by TorchFX-to-NNTrainer converter")
    L.append(f"// Model: {s.model_type} ({s.arch_type})")
    L.append(f"// Inherits from causallm::{base_class}")
    L.append(f"")
    L.append(f"#ifndef {guard}")
    L.append(f"#define {guard}")
    L.append(f"")
    L.append(f'#include "{base_header}"')
    L.append(f"")

    L.append(f"namespace causallm {{")
    L.append(f"")

    if need_variant:
        # Emit a Transformer variant class (like Qwen3Transformer)
        variant_name = cname.replace("CausalLM", "Transformer").replace(
            "Model", "Transformer")
        L.append(f"/**")
        L.append(f" * @brief {variant_name} - model-specific attention variant")
        L.append(f" * @note Overrides createAttention() for {s.model_type}-specific behavior")
        L.append(f" */")
        L.append(f"class {variant_name} : virtual public Transformer {{")
        L.append(f"public:")
        L.append(f"  {variant_name}(json &cfg, json &generation_cfg, json &nntr_cfg)")
        L.append(f"    : Transformer(cfg, generation_cfg, nntr_cfg) {{}}")
        L.append(f"")
        L.append(f"  Tensor createAttention(const int layer_id, int seq_len,")
        L.append(f"                         int n_heads, int head_dim,")
        L.append(f"                         Tensor query, Tensor key,")
        L.append(f"                         Tensor value) override;")
        L.append(f"")
        L.append(f"  void registerCustomLayers() override;")
        L.append(f"}};")
        L.append(f"")

    # Detect architectural differences for override declarations
    block = s.blocks[0] if s.blocks else None
    from .helpers import get_norm_type as _get_norm_type
    _norm_type = _get_norm_type(s.model_type)
    is_post_norm = block and block.norm_type == "post_norm"
    uses_layer_norm = _norm_type == "layer_normalization"
    no_rope = attn_block and not attn_block.attention.has_rope
    is_encoder_only = s.arch_type == "encoder_only"

    op_types = set(b.operator_type for b in s.blocks) if s.blocks else set()
    is_hybrid = len(op_types) > 1
    has_conv = "conv" in op_types

    need_override_construct = (is_encoder_only or is_post_norm or
                               uses_layer_norm or is_hybrid)
    need_override_block = is_post_norm or uses_layer_norm
    need_override_attention = (no_rope or uses_layer_norm) and not need_variant
    need_override_setup = uses_layer_norm or no_rope

    # Main class
    L.append(f"/**")
    L.append(f" * @brief {cname} Class")
    L.append(f" * @note Auto-generated from HuggingFace {s.model_type} model")
    L.append(f" */")
    if need_variant:
        variant_name = cname.replace("CausalLM", "Transformer").replace(
            "Model", "Transformer")
        L.append(f"class {cname} : public {base_class}, "
                 f"public {variant_name} {{")
    else:
        L.append(f"class {cname} : public {base_class} {{")
    L.append(f"")
    L.append(f"public:")

    # JSON config constructor
    if need_variant:
        variant_name = cname.replace("CausalLM", "Transformer").replace(
            "Model", "Transformer")
        L.append(f"  {cname}(json &cfg, json &generation_cfg, json &nntr_cfg)")
        L.append(f"    : Transformer(cfg, generation_cfg, nntr_cfg, "
                 f"ModelType::CAUSALLM),")
        L.append(f"      {base_class}(cfg, generation_cfg, nntr_cfg),")
        L.append(f"      {variant_name}(cfg, generation_cfg, nntr_cfg) {{}}")
    elif base_class == "Transformer":
        mt = "ModelType::MODEL"
        L.append(f"  {cname}(json &cfg, json &generation_cfg, json &nntr_cfg)")
        L.append(f"    : Transformer(cfg, generation_cfg, nntr_cfg, {mt}) {{}}")
    else:
        mt = "ModelType::CAUSALLM"
        L.append(f"  {cname}(json &cfg, json &generation_cfg, json &nntr_cfg)")
        L.append(f"    : Transformer(cfg, generation_cfg, nntr_cfg, {mt}),")
        L.append(f"      {base_class}(cfg, generation_cfg, nntr_cfg) {{}}")
    L.append(f"")

    # Override declarations for methods that differ from base
    if need_override_setup:
        L.append(f"  void setupParameters(json &cfg, json &generation_cfg,")
        L.append(f"                       json &nntr_cfg) override;")

    if need_override_construct:
        L.append(f"  void constructModel() override;")

    if has_conv:
        L.append(f"  Tensor createConvBlock(const int layer_id,")
        L.append(f"                         Tensor input);")

    if need_override_block:
        L.append(f"  Tensor createTransformerDecoderBlock(const int layer_id,")
        L.append(f"                                      Tensor input) override;")

    if need_override_attention:
        L.append(f"  Tensor createAttention(const int layer_id, int seq_len,")
        L.append(f"                         int n_heads, int head_dim,")
        L.append(f"                         Tensor query, Tensor key,")
        L.append(f"                         Tensor value) override;")

    # Non-SwiGLU FFN needs createMlp override
    ffn_block = block.ffn if block else None
    if ffn_block and ffn_block.ffn_type not in ("swiglu",):
        L.append(f"  Tensor createMlp(const int layer_id, int dim,")
        L.append(f"                   int hidden_dim, Tensor input) override;")

    L.append(f"  void registerCustomLayers() override;")
    L.append(f"")

    # Test-only factory
    L.append(f"  /**")
    L.append(f"   * @brief Test constructor with minimal config")
    L.append(f"   * @note Creates model with small dimensions for testing")
    L.append(f"   */")
    L.append(f"  static {cname} createTestModel();")
    L.append(f"")

    L.append(f"  ModelHandle &getModel() {{ return model; }}")
    L.append(f"}};")
    L.append(f"")
    L.append(f"}} // namespace causallm")
    L.append(f"")
    L.append(f"#endif // {guard}")
    L.append(f"")
    return "\n".join(L)


def _emit_standalone_header(structure, blocks_info, model_name):
    """Generate standalone header (original behavior, no Transformer inheritance)."""
    s = structure
    cname = _class_name(s.model_type, s.arch_type)
    base = get_file_base(s, model_name)
    guard = f"__{base.upper()}_H__"

    attn_block = blocks_info["attn_block"]
    is_hybrid = blocks_info["is_hybrid"]
    op_types = blocks_info["op_types"]

    L = []
    L.append(f"// Auto-generated by TorchFX-to-NNTrainer converter")
    L.append(f"// Model: {s.model_type} ({s.arch_type})")
    L.append(f"")
    L.append(f"#ifndef {guard}")
    L.append(f"#define {guard}")
    L.append(f"")
    L.append(f"#include <climits>")
    L.append(f"#include <layer.h>")
    L.append(f"#include <model.h>")
    L.append(f"#include <tensor_api.h>")
    L.append(f"")

    has_qk_norm = attn_block and attn_block.attention.has_qk_norm
    if has_qk_norm:
        L.append(f"#include <reshaped_rms_norm.h>")
        L.append(f"")

    L.append(f"using LayerHandle = ml::train::LayerHandle;")
    L.append(f"using Tensor = ml::train::Tensor;")
    L.append(f"using ModelHandle = std::unique_ptr<ml::train::Model>;")
    L.append(f"")

    if s.external_kv_cache:
        L.append(f"/**")
        L.append(f" * @brief External KV cache buffers (owned by the model class)")
        L.append(f" */")
        L.append(f"struct KVCacheBuffers {{")
        L.append(f"  std::vector<std::vector<float>> key_buffers;")
        L.append(f"  std::vector<std::vector<float>> value_buffers;")
        L.append(f"")
        L.append(f"  void allocate(unsigned int num_layers, size_t cache_size) {{")
        L.append(f"    key_buffers.resize(num_layers);")
        L.append(f"    value_buffers.resize(num_layers);")
        L.append(f"    for (unsigned int i = 0; i < num_layers; ++i) {{")
        L.append(f"      key_buffers[i].resize(cache_size, 0.0f);")
        L.append(f"      value_buffers[i].resize(cache_size, 0.0f);")
        L.append(f"    }}")
        L.append(f"  }}")
        L.append(f"}};")
        L.append(f"")

    L.append(f"/**")
    L.append(f" * @brief {cname} Class")
    L.append(f" * @note Auto-generated from HuggingFace {s.model_type} model")
    L.append(f" */")
    L.append(f"class {cname} {{")
    L.append(f"")
    L.append(f"public:")
    L.append(f"  {cname}();")
    L.append(f"  virtual ~{cname}() = default;")
    L.append(f"")
    L.append(f"  /**")
    L.append(f"   * @brief Construct the model graph")
    L.append(f"   */")
    L.append(f"  virtual void constructModel();")
    L.append(f"")
    L.append(f"  /**")
    L.append(f"   * @brief Initialize the model (register layers, construct, compile)")
    L.append(f"   */")
    L.append(f"  virtual void initialize();")
    L.append(f"")
    L.append(f"  /**")
    L.append(f"   * @brief Get the underlying model handle")
    L.append(f"   */")
    L.append(f"  ModelHandle &getModel() {{ return model; }}")
    L.append(f"")
    L.append(f"protected:")

    # Block creation methods - now return Tensor and accept Tensor
    if s.arch_type == "encoder_decoder":
        _emit_enc_dec_block_decls(L)
    else:
        block_type = ("DecoderBlock" if s.arch_type == "decoder_only"
                      else "Block")
        for op_type in op_types:
            op_label = op_type.capitalize() if op_type != "attention" \
                else "Transformer"
            L.append(f"  /**")
            L.append(f"   * @brief Create a {op_label} {block_type}")
            L.append(f"   */")
            method_name = (f"createTransformer{block_type}"
                           if op_type == "attention"
                           else f"create{op_label}{block_type}")
            L.append(f"  virtual Tensor")
            L.append(f"  {method_name}("
                     f"const int layer_id, Tensor input);")
            L.append(f"")

    # createAttention - now accepts/returns Tensor
    if attn_block:
        L.append(f"  /**")
        L.append(f"   * @brief Create Attention layers")
        L.append(f"   */")
        L.append(f"  virtual Tensor")
        L.append(f"  createAttention(const int layer_id, int seq_len, "
                 f"int n_heads, int head_dim,")
        L.append(f"                  Tensor query, "
                 f"Tensor key, Tensor value);")
        L.append(f"")

    # createMlp - now accepts/returns Tensor
    L.append(f"  /**")
    L.append(f"   * @brief Create Feed Forward layers")
    L.append(f"   */")
    L.append(f"  virtual Tensor")
    L.append(f"  createMlp(const int layer_id, int dim, int hidden_dim,")
    L.append(f"            Tensor input);")
    L.append(f"")

    # allocateKVCache (external mode)
    if s.external_kv_cache:
        L.append(f"  /**")
        L.append(f"   * @brief Allocate external KV cache buffers")
        L.append(f"   */")
        L.append(f"  void allocateKVCache();")
        L.append(f"")

    # registerCustomLayers
    L.append(f"  /**")
    L.append(f"   * @brief Register custom layers")
    L.append(f"   */")
    L.append(f"  virtual void registerCustomLayers();")
    L.append(f"")

    # Member variables
    _emit_member_variables(L, s, attn_block)

    L.append(f"}};")
    L.append(f"")
    L.append(f"#endif // {guard}")
    L.append(f"")
    return "\n".join(L)


def _emit_enc_dec_block_decls(L):
    """Emit encoder/decoder block method declarations."""
    L.append(f"  /**")
    L.append(f"   * @brief Create a Transformer Encoder Block")
    L.append(f"   */")
    L.append(f"  virtual Tensor")
    L.append(f"  createEncoderBlock("
             f"const int layer_id, Tensor input);")
    L.append(f"")
    L.append(f"  /**")
    L.append(f"   * @brief Create a Transformer Decoder Block")
    L.append(f"   */")
    L.append(f"  virtual Tensor")
    L.append(f"  createDecoderBlock("
             f"const int layer_id, Tensor input,")
    L.append(f"                     "
             f"Tensor encoder_output);")
    L.append(f"")


def _emit_member_variables(L, s, attn_block):
    """Emit class member variable declarations."""
    L.append(f"  ModelHandle model;")
    L.append(f"")

    if s.external_kv_cache:
        L.append(f"  KVCacheBuffers kv_cache_buffers;")
        L.append(f"  std::vector<Tensor> key_cache_tensors;")
        L.append(f"  std::vector<Tensor> val_cache_tensors;")
        L.append(f"")

    L.append(f"  // Model constants")
    L.append(f"  unsigned int NUM_VOCAB = {s.vocab_size};")
    L.append(f"  int DIM = {s.hidden_size};")
    if s.arch_type == "encoder_decoder":
        L.append(f"  int NUM_ENCODER_LAYERS = {s.num_encoder_layers};")
        L.append(f"  int NUM_DECODER_LAYERS = {s.num_decoder_layers};")
    L.append(f"  int NUM_LAYERS = {s.num_layers};")
    L.append(f"  int NUM_HEADS = {s.num_heads};")
    L.append(f"  int NUM_KV_HEADS = {s.num_kv_heads};")
    L.append(f"  int HEAD_DIM = {s.head_dim};")
    L.append(f"  int INTERMEDIATE_SIZE = {s.intermediate_size};")
    L.append(f"  std::string NORM_EPS = \"{s.norm_eps or 1e-6}\";")
    if s.rope_theta:
        L.append(f"  unsigned int ROPE_THETA = {int(s.rope_theta)};")
    L.append(f"  bool TIE_WORD_EMBEDDINGS = "
             f"{'true' if s.tie_word_embeddings else 'false'};")

    if s.num_kv_heads and s.num_heads:
        gqa = s.num_heads // s.num_kv_heads
        L.append(f"  int GQA_SIZE = {gqa};")

    is_decoder = s.arch_type in ("decoder_only", "encoder_decoder")

    if attn_block and is_decoder:
        L.append(f"  unsigned int SLIDING_WINDOW = UINT_MAX;")

    if s.conv_l_cache:
        L.append(f"  int CONV_KERNEL_SIZE = {s.conv_l_cache};")

    L.append(f"  unsigned int INIT_SEQ_LEN = 0;")
    if is_decoder:
        L.append(f"  unsigned int NUM_TO_GENERATE = 0;")
    if attn_block and attn_block.attention.has_rope:
        L.append(f"  unsigned int MAX_POSITION_EMBEDDINGS = "
                 f"{s.max_position_embeddings or 2048};")
