"""C++ source generation for Transformer-inheriting models.

Generates overridden methods that differ from the base Transformer class.
The base class (CausalLM/Transformer) provides default implementations for
decoder-only models with pre-norm, RoPE, SwiGLU.

For encoder-only models (BERT), the following differences must be overridden:
- constructModel(): different embedding (token + position + token_type), post-norm
- createTransformerDecoderBlock(): post-norm instead of pre-norm, LayerNorm
- createAttention(): no RoPE, bias enabled, bidirectional
- createMlp(): GELU instead of SwiGLU
- setupParameters(): different config keys (layer_norm_eps vs rms_norm_eps)
"""

from .helpers import _class_name, _cpp_tensor_layer, get_file_base, get_norm_type
from .source_attention import emit_attention_method
from .source_ffn import emit_ffn_method
from .source_custom import (
    collect_custom_layer_classes, emit_custom_layer_includes,
    CUSTOM_LAYER_CLASS,
)


def _get_arch_diffs(structure, attn_block):
    """Detect architectural differences from the Transformer base class.

    Returns a dict describing what needs to be overridden.
    """
    s = structure
    norm_type = get_norm_type(s.model_type)
    block = s.blocks[0] if s.blocks else None

    # Detect hybrid architecture (conv + attention blocks)
    op_types = set(b.operator_type for b in s.blocks) if s.blocks else set()
    is_hybrid = len(op_types) > 1
    has_conv = "conv" in op_types

    diffs = {
        "is_encoder_only": s.arch_type == "encoder_only",
        "is_post_norm": block and block.norm_type == "post_norm",
        "uses_layer_norm": norm_type == "layer_normalization",
        "no_rope": attn_block and not attn_block.attention.has_rope,
        "has_bias": True if norm_type == "layer_normalization" else False,
        "non_swiglu_ffn": (block and block.ffn and
                           block.ffn.ffn_type not in ("swiglu",)),
        "has_qk_norm": attn_block and attn_block.attention.has_qk_norm,
        "has_position_embedding": s.arch_type == "encoder_only",
        "has_token_type_embedding": s.arch_type == "encoder_only",
        "is_hybrid": is_hybrid,
        "has_conv": has_conv,
    }

    # Determine which methods need overriding
    diffs["override_construct_model"] = (
        diffs["has_position_embedding"] or
        diffs["has_token_type_embedding"] or
        diffs["is_post_norm"] or
        diffs["uses_layer_norm"] or
        diffs["is_hybrid"]  # Hybrid needs custom block dispatch
    )
    diffs["override_block"] = (
        diffs["is_post_norm"] or
        diffs["uses_layer_norm"]
    )
    diffs["override_attention"] = (
        diffs["no_rope"] or
        diffs["has_bias"] or
        diffs["has_qk_norm"]
    )
    diffs["override_mlp"] = diffs["non_swiglu_ffn"]
    diffs["override_setup_params"] = (
        diffs["uses_layer_norm"] or
        diffs["no_rope"]
    )

    return diffs


def emit_inherit_source(structure, attn_block, custom_classes, model_name,
                        layers=None):
    """Generate source file for Transformer-inheriting model.

    Analyzes architectural differences from the base Transformer class
    and emits only the methods that need to be overridden.

    Args:
        layers: Full list of NNTrainerLayerDef from conversion result.
                Needed for hybrid models to emit conv block tensor ops.
    """
    s = structure
    cname = _class_name(s.model_type, s.arch_type)
    header_file = get_file_base(s, model_name) + ".h"
    norm_type = get_norm_type(s.model_type)
    diffs = _get_arch_diffs(s, attn_block)

    has_lm_head = bool(s.lm_head)
    has_qk_norm = diffs["has_qk_norm"]
    need_variant = has_qk_norm

    if has_lm_head and s.arch_type == "decoder_only":
        base_class = "CausalLM"
    else:
        base_class = "Transformer"

    variant_name = cname.replace("CausalLM", "Transformer").replace(
        "Model", "Transformer") if need_variant else None

    L = []
    L.append(f"// Auto-generated by TorchFX-to-NNTrainer converter")
    L.append(f"// Model: {s.model_type} ({s.arch_type})")
    L.append(f"// Inherits from causallm::{base_class}")
    L.append(f"")
    L.append(f'#include "{header_file}"')
    L.append(f"#include <model.h>")
    L.append(f"#include <tensor_api.h>")
    L.append(f"#include <app_context.h>")
    L.append(f"#include <engine.h>")
    L.append(f"")

    includes = emit_custom_layer_includes(custom_classes)
    if includes:
        L.append(includes)
        L.append(f"")

    L.append(f"using ml::train::createLayer;")
    L.append(f"using ml::train::Tensor;")
    L.append(f"using LayerHandle = ml::train::LayerHandle;")
    L.append(f"")

    # withKey helper templates
    L.append("template <typename T>")
    L.append('static std::string withKey(const std::string &key, T val) {')
    L.append('  return key + "=" + std::to_string(val);')
    L.append("}")
    L.append("")
    L.append("template <>")
    L.append('std::string withKey(const std::string &key, '
             'std::string val) {')
    L.append('  return key + "=" + val;')
    L.append("}")
    L.append("")
    L.append("template <>")
    L.append('std::string withKey(const std::string &key, '
             'const char *val) {')
    L.append('  return key + "=" + std::string(val);')
    L.append("}")
    L.append("")

    L.append(f"namespace causallm {{")
    L.append(f"")

    # --- Variant class methods (e.g., Qwen3Transformer::createAttention) ---
    if need_variant:
        # createAttention override on variant class
        if attn_block:
            attn_code = emit_attention_method(
                variant_name, attn_block,
                arch_type=s.arch_type,
                external_kv_cache=s.external_kv_cache)
            L.append(attn_code)

        # registerCustomLayers for variant
        L.append(f"void {variant_name}::registerCustomLayers() {{")
        variant_classes = set()
        if has_qk_norm:
            variant_classes.add("ReshapedRMSNormLayer")
        _emit_layer_registration(L, sorted(variant_classes))
        L.append(f"}}")
        L.append(f"")

    # --- Main class methods ---

    # setupParameters override for encoder-only models
    if diffs["override_setup_params"]:
        _emit_setup_parameters_override(L, cname, s, diffs)

    # constructModel override for hybrid or encoder-only models
    if diffs["override_construct_model"]:
        _emit_construct_model_override(L, cname, s, diffs, norm_type)

    # createConvBlock for hybrid models with conv layers
    if diffs["has_conv"] and layers:
        _emit_conv_block_method(L, cname, s, layers)

    # createTransformerDecoderBlock override for post-norm models
    if diffs["override_block"]:
        _emit_block_override(L, cname, s, diffs, norm_type)

    # createAttention override for models without RoPE or with bias
    if diffs["override_attention"] and not need_variant:
        _emit_attention_override(L, cname, s, attn_block, diffs)

    # registerCustomLayers: combines base + variant registrations
    L.append(f"void {cname}::registerCustomLayers() {{")
    if need_variant:
        L.append(f"  {base_class}::registerCustomLayers();")
        L.append(f"  {variant_name}::registerCustomLayers();")
    else:
        L.append(f"  {base_class}::registerCustomLayers();")
        # Register any extra custom layers not in base
        extra = _get_extra_custom_classes(custom_classes, base_class)
        if extra:
            _emit_layer_registration(L, extra)
    L.append(f"}}")
    L.append(f"")

    # createMlp override if non-SwiGLU FFN
    ffn_block = next((b for b in s.blocks if b.ffn), None)
    if diffs["override_mlp"] and ffn_block:
        L.append(emit_ffn_method(cname, ffn_block))

    # createTestModel: factory method for standalone testing
    _emit_test_factory(L, cname, s, need_variant, base_class, variant_name,
                       diffs)

    L.append(f"}} // namespace causallm")
    L.append(f"")
    return "\n".join(L)


def _emit_layer_registration(L, classes):
    """Emit registerFactory calls for a set of custom layer classes."""
    L.append(f"  auto &ct_engine = nntrainer::Engine::Global();")
    L.append(f'  auto app_context =')
    L.append(f'    static_cast<nntrainer::AppContext *>('
             f'ct_engine.getRegisteredContext("cpu"));')
    L.append(f"  try {{")
    for cls in classes:
        L.append(f"    app_context->registerFactory("
                 f"nntrainer::createLayer<causallm::{cls}>);")
    L.append(f"  }} catch (std::invalid_argument &e) {{")
    L.append(f'    std::cerr << "failed to register factory, reason: " '
             f'<< e.what() << std::endl;')
    L.append(f"  }}")


def _get_extra_custom_classes(all_classes, base_class):
    """Return custom classes that aren't already registered by the base."""
    base_registered = {
        "SwiGLULayer", "RMSNormLayer", "MHACoreLayer",
        "TieWordEmbedding", "EmbeddingLayer",
    }
    if base_class == "CausalLM":
        base_registered.add("LmHeadLayer")
    return sorted(set(all_classes) - base_registered)


# -------------------------------------------------------------------------
# Override emitters for encoder-only (BERT-like) models
# -------------------------------------------------------------------------

def _emit_setup_parameters_override(L, cname, s, diffs):
    """Emit setupParameters() override for models with different config keys.

    BERT uses layer_norm_eps (not rms_norm_eps) and has no rope_theta.
    """
    norm_eps_key = "layer_norm_eps" if diffs["uses_layer_norm"] else "rms_norm_eps"

    L.append(f"void {cname}::setupParameters(json &cfg, json &generation_cfg,")
    L.append(f"                              json &nntr_cfg) {{")
    L.append(f"")
    L.append(f"  // nntrainer parameters")
    L.append(f'  BATCH_SIZE = nntr_cfg["batch_size"].get<unsigned int>();')
    L.append(f'  MODEL_TENSOR_TYPE = nntr_cfg["model_tensor_type"]'
             f'.get<std::string>();')
    L.append(f'  INIT_SEQ_LEN = nntr_cfg["init_seq_len"];')
    L.append(f'  MAX_SEQ_LEN = nntr_cfg.value("max_seq_len", INIT_SEQ_LEN);')
    L.append(f'  NUM_TO_GENERATE = nntr_cfg.value("num_to_generate", 0);')
    L.append(f'  MEMORY_SWAP = nntr_cfg.value("fsu", false);')
    L.append(f'  FSU_LOOKAHEAD = nntr_cfg.value("fsu_lookahead", 1u);')
    L.append(f'  EMBEDDING_DTYPE = nntr_cfg.value("embedding_dtype",'
             f' MODEL_TENSOR_TYPE);')
    L.append(f'  FC_LAYER_DTYPE = nntr_cfg.value("fc_layer_dtype",'
             f' MODEL_TENSOR_TYPE);')
    L.append(f"")

    # is_causal
    if diffs["is_encoder_only"]:
        L.append(f"  // Encoder-only model: bidirectional attention")
        L.append(f"  IS_CAUSAL = false;")
    else:
        L.append(f"  IS_CAUSAL = cfg.value(\"is_causal\", true);")
    L.append(f"")

    L.append(f"  // Model architecture parameters")
    L.append(f'  NUM_VOCAB = cfg["vocab_size"];')
    L.append(f'  DIM = cfg["hidden_size"];')
    L.append(f'  INTERMEDIATE_SIZE = cfg["intermediate_size"];')
    L.append(f'  NUM_LAYERS = cfg["num_hidden_layers"];')
    L.append(f'  NUM_HEADS = cfg["num_attention_heads"];')
    L.append(f'  HEAD_DIM = cfg.value("head_dim", DIM / NUM_HEADS);')
    L.append(f'  NUM_KEY_VALUE_HEADS = cfg.value("num_key_value_heads",'
             f' NUM_HEADS);')
    L.append(f'  MAX_POSITION_EMBEDDINGS = cfg.value('
             f'"max_position_embeddings", 512u);')
    L.append(f'  TIE_WORD_EMBEDDINGS = cfg.value("tie_word_embeddings",'
             f' false);')
    L.append(f'  NORM_EPS = cfg.value("{norm_eps_key}", 1e-12f);')

    if diffs["no_rope"]:
        L.append(f"  ROPE_THETA = 0;  // No RoPE for this model")
    else:
        L.append(f'  ROPE_THETA = cfg.value("rope_theta", 10000u);')

    L.append(f"  GQA_SIZE = NUM_HEADS / NUM_KEY_VALUE_HEADS;")
    L.append(f'  SLIDING_WINDOW = cfg.value("sliding_window", UINT_MAX);')
    L.append(f"}}")
    L.append(f"")


def _emit_construct_model_override(L, cname, s, diffs, norm_type):
    """Emit constructModel() override.

    Handles:
    - Encoder-only: multiple embeddings, post-embedding norm
    - Hybrid: per-layer type dispatch (conv vs attention blocks)
    """
    is_hybrid = diffs.get("is_hybrid", False)
    is_encoder_only = diffs.get("is_encoder_only", False)

    L.append(f"void {cname}::constructModel() {{")
    L.append(f"")
    L.append(f"  using ml::train::createLayer;")
    L.append(f"")

    if is_encoder_only:
        # Encoder-only: custom input/embedding handling
        L.append(f"  // Input layer")
        L.append(f'  LayerHandle input_layer(createLayer("input", {{')
        L.append(f'    withKey("name", "input0"),')
        L.append(f'    withKey("input_shape", "1:1:" +'
                 f' std::to_string(INIT_SEQ_LEN))')
        L.append(f"  }}));")
        L.append(f"  Tensor input = input_layer(Tensor());")
        L.append(f"  std::vector<Tensor> all_inputs = {{input}};")
        L.append(f"")

        if diffs["has_position_embedding"]:
            L.append(f"  // Position IDs input")
            L.append(f'  LayerHandle pos_input(createLayer("input", {{')
            L.append(f'    withKey("name", "position_ids"),')
            L.append(f'    withKey("input_shape", "1:1:" +'
                     f' std::to_string(INIT_SEQ_LEN))')
            L.append(f"  }}));")
            L.append(f"  Tensor pos_ids = pos_input(Tensor());")
            L.append(f"  all_inputs.push_back(pos_ids);")
            L.append(f"")

        if diffs["has_token_type_embedding"]:
            L.append(f"  // Token type IDs input")
            L.append(f'  LayerHandle tt_input(createLayer("input", {{')
            L.append(f'    withKey("name", "token_type_ids"),')
            L.append(f'    withKey("input_shape", "1:1:" +'
                     f' std::to_string(INIT_SEQ_LEN))')
            L.append(f"  }}));")
            L.append(f"  Tensor tt_ids = tt_input(Tensor());")
            L.append(f"  all_inputs.push_back(tt_ids);")
            L.append(f"")

        # Token embedding
        L.append(f"  // Token embedding")
        if s.tie_word_embeddings:
            L.append(f'  const std::string embedding_type = '
                     f'TIE_WORD_EMBEDDINGS ? '
                     f'"tie_word_embeddings" : "embedding_layer";')
        else:
            L.append(f'  const std::string embedding_type = '
                     f'"embedding_layer";')
        L.append(f'  LayerHandle word_emb(createLayer(embedding_type, {{')
        L.append(f'    withKey("name", "embedding0"),')
        L.append(f'    withKey("in_dim", NUM_VOCAB),')
        L.append(f'    withKey("out_dim", DIM)')
        L.append(f"  }}));")
        L.append(f"  Tensor x = word_emb(input);")
        L.append(f"")

        if diffs["has_position_embedding"]:
            L.append(f"  // Position embedding")
            L.append(f'  LayerHandle pos_emb(createLayer("embedding_layer", '
                     f'{{')
            L.append(f'    withKey("name", "position_embedding"),')
            L.append(f'    withKey("in_dim", MAX_POSITION_EMBEDDINGS),')
            L.append(f'    withKey("out_dim", DIM)')
            L.append(f"  }}));")
            L.append(f"  Tensor pos_out = pos_emb(pos_ids);")
            L.append(f"  x = x.add(pos_out);")
            L.append(f"")

        if diffs["has_token_type_embedding"]:
            type_vocab = getattr(s, 'type_vocab_size', 2) or 2
            L.append(f"  // Token type embedding")
            L.append(f'  LayerHandle tt_emb(createLayer("embedding_layer", '
                     f'{{')
            L.append(f'    withKey("name", "token_type_embedding"),')
            L.append(f'    withKey("in_dim", {type_vocab}),')
            L.append(f'    withKey("out_dim", DIM)')
            L.append(f"  }}));")
            L.append(f"  Tensor tt_out = tt_emb(tt_ids);")
            L.append(f"  x = x.add(tt_out);")
            L.append(f"")

        # Post-embedding LayerNorm (BERT-style)
        L.append(f"  // Post-embedding normalization")
        L.append(f'  LayerHandle emb_norm(createLayer("{norm_type}", {{')
        L.append(f'    withKey("name", "embedding_norm"),')
        L.append(f'    withKey("epsilon", std::to_string(NORM_EPS))')
        if norm_type == "layer_normalization":
            L.append(f'    , withKey("axis", 3)')
        elif norm_type == "rms_norm":
            L.append(f'    , withKey("packed", "false")')
        L.append(f"  }}));")
        L.append(f"  x = emb_norm(x);")
        L.append(f"")

        # Transformer blocks
        L.append(f"  // Transformer encoder blocks")
        L.append(f"  for (int i = 0; i < NUM_LAYERS; ++i) {{")
        L.append(f"    x = createTransformerDecoderBlock(i, x);")
        L.append(f"  }}")
        L.append(f"")

        # Compile
        L.append(f"  // Compile model from symbolic tensor graph")
        L.append(f"  std::vector<Tensor> outputs = {{x}};")
        L.append(f"  model->compile(all_inputs, outputs, "
                 f"ml::train::ExecutionMode::INFERENCE);")

    elif is_hybrid:
        # Hybrid: use base Transformer's input/embedding/norm,
        # but override the block loop with per-layer type dispatch
        op_type_list = [b.operator_type for b in s.blocks]
        op_types_unique = sorted(set(op_type_list))

        L.append(f"  // Create input tensor")
        L.append(f'  LayerHandle input_layer = createLayer("input", {{')
        L.append(f'    withKey("name", "input0"),')
        L.append(f'    withKey("input_shape", "1:1:" +'
                 f' std::to_string(INIT_SEQ_LEN))')
        L.append(f"  }});")
        L.append(f"  Tensor input = input_layer(Tensor());")
        L.append(f"  std::vector<Tensor> all_inputs = {{input}};")
        L.append(f"")

        # Embedding (same as base Transformer)
        L.append(f"  // Embedding layer")
        if s.tie_word_embeddings:
            L.append(f'  const std::string embedding_type = '
                     f'TIE_WORD_EMBEDDINGS ? '
                     f'"tie_word_embeddings" : "embedding_layer";')
        else:
            L.append(f'  const std::string embedding_type = '
                     f'"embedding_layer";')
        L.append(f'  LayerHandle embedding(createLayer(embedding_type, {{')
        L.append(f'    withKey("name", "embedding0"),')
        L.append(f'    withKey("in_dim", NUM_VOCAB),')
        L.append(f'    withKey("out_dim", DIM)')
        L.append(f"  }}));")
        L.append(f"  Tensor x = embedding(input);")
        L.append(f"")

        # Layer types array
        L.append(f"  // Per-layer operator types")
        L.append(f"  const std::vector<std::string> LAYER_TYPES = {{")
        for i, ot in enumerate(op_type_list):
            comma = "," if i < len(op_type_list) - 1 else ""
            L.append(f'    "{ot}"{comma}')
        L.append(f"  }};")
        L.append(f"")

        # Hybrid block loop
        L.append(f"  // Hybrid transformer blocks")
        L.append(f"  for (int i = 0; i < NUM_LAYERS; ++i) {{")
        for idx, op_type in enumerate(op_types_unique):
            keyword = "if" if idx == 0 else "} else if"
            if op_type == "attention":
                L.append(f'    {keyword} (LAYER_TYPES[i] == "attention") {{')
                L.append(f"      x = createTransformerDecoderBlock(i, x);")
            else:
                method = f"create{op_type.capitalize()}Block"
                L.append(f'    {keyword} (LAYER_TYPES[i] == "{op_type}") {{')
                L.append(f"      x = {method}(i, x);")
        L.append(f"    }}")
        L.append(f"  }}")
        L.append(f"")

        # Final norm
        L.append(f"  // Final normalization")
        L.append(f'  LayerHandle output_norm(createLayer("rms_norm", {{')
        L.append(f'    withKey("name", "output_norm"),')
        L.append(f'    withKey("epsilon", std::to_string(NORM_EPS)),')
        L.append(f'    withKey("packed", "false")')
        L.append(f"  }}));")
        L.append(f"  Tensor norm_out = output_norm(x);")
        L.append(f"")

        # LM head
        if s.lm_head:
            L.append(f"  // LM head")
            if s.tie_word_embeddings:
                L.append(f'  const std::string lmhead_type = '
                         f'TIE_WORD_EMBEDDINGS ? '
                         f'"tie_word_embeddings" : "fully_connected";')
            else:
                L.append(f'  const std::string lmhead_type = '
                         f'"fully_connected";')
            L.append(f'  std::vector<std::string> lmhead_props = {{')
            L.append(f'    withKey("name", "output_of_causallm"),')
            L.append(f'    withKey("unit", NUM_VOCAB),')
            L.append(f'    withKey("disable_bias", "true")')
            if s.tie_word_embeddings:
                L.append(f'    , withKey("shared_from", "embedding0")')
            L.append(f"  }};")
            L.append(f"  LayerHandle lmhead(createLayer(lmhead_type, "
                     f"lmhead_props));")
            L.append(f"  Tensor output = lmhead(norm_out);")
            L.append(f"")
            output_var = "output"
        else:
            output_var = "norm_out"

        # Compile
        L.append(f"  // Compile model from symbolic tensor graph")
        L.append(f"  model->compile(input, {output_var}, "
                 f"ml::train::ExecutionMode::INFERENCE);")

    L.append(f"}}")
    L.append(f"")


def _emit_conv_block_method(L, cname, s, layers):
    """Emit createConvBlock() method for hybrid models.

    Generates a complete conv block with all tensor operations from the
    conversion result layers (transpose, split, multiply, conv1d, slice, etc).

    Split/chunk operations produce multi-output tensors whose individual
    outputs are accessed via operator.getitem in PyTorch.  In the converter
    pipeline these getitem results become standalone ``input`` layers with
    names like ``getitem``, ``getitem_1``, etc.  This method detects such
    references, emits ``Tensor::output(N)`` calls after the split layer,
    and wires the indexed outputs into downstream operations.
    """
    # Find the conv block pattern from structure
    conv_block = None
    for b in s.blocks:
        if b.operator_type == "conv":
            conv_block = b
            break

    if conv_block is None:
        return

    # Get the scope prefix to identify conv layers for block 0
    scope = conv_block.operator_scope  # e.g. "model.layers.0.conv"
    scope_san = scope.replace(".", "_")
    # Find the block-level prefix: "model_layers_0"
    # scope_san is like "model_layers_0_conv"
    block_prefix = scope_san.rsplit("_", 1)[0] if "_conv" in scope_san \
        else scope_san

    # Collect all layers belonging to this conv block
    conv_layers = []
    for layer in layers:
        if layer.name.startswith(scope_san):
            conv_layers.append(layer)

    # --- Resolve split → getitem mapping ---
    # Find getitem references: input_layers names referenced by conv layers
    # but not defined in the conv layer set themselves.
    conv_layer_names = {la.name for la in conv_layers}
    getitem_refs = set()
    for la in conv_layers:
        for inp in la.input_layers:
            if inp not in conv_layer_names and inp.startswith("getitem"):
                getitem_refs.add(inp)

    # Build getitem → index mapping (getitem=0, getitem_1=1, getitem_2=2, …)
    def _getitem_index(name):
        if name == "getitem":
            return 0
        parts = name.rsplit("_", 1)
        if len(parts) == 2 and parts[1].isdigit():
            return int(parts[1])
        return 0

    getitem_sorted = sorted(getitem_refs, key=_getitem_index)

    # Find which split layer in conv_layers these getitems belong to.
    # There is typically exactly one split/chunk per conv block.
    split_layer_name = None
    for la in conv_layers:
        if la.layer_type == "split":
            split_layer_name = la.name
            break

    L.append(f"Tensor")
    L.append(f"{cname}::createConvBlock(const int layer_id,")
    L.append(f"  Tensor input) {{")
    L.append(f"")
    L.append(f"  using ml::train::createLayer;")
    L.append(f'  auto prefix = "layer" + std::to_string(layer_id);')
    L.append(f"")

    # Pre-conv normalization (from base Transformer pattern)
    L.append(f"  // Pre-conv normalization")
    L.append(f'  LayerHandle conv_norm(createLayer("rms_norm", {{')
    L.append(f'    withKey("name", prefix + "_conv_norm"),')
    L.append(f'    withKey("epsilon", std::to_string(NORM_EPS)),')
    L.append(f'    withKey("packed", "false")')
    L.append(f"  }}));")
    L.append(f"  Tensor normed = conv_norm(input);")
    L.append(f"")

    # Emit conv operator layers as tensor ops
    L.append(f"  // Conv operator (tensor-level operations)")
    tensor_vars = {"normed": "normed"}
    prev_var = "normed"
    var_idx = 0

    for layer in conv_layers:
        var_name = f"conv_op_{var_idx}"
        var_idx += 1

        # Determine the suffix for parameterized naming
        if layer.name.startswith(scope_san + "_"):
            suffix = layer.name[len(scope_san):]
        elif layer.name.startswith(block_prefix + "_conv_"):
            suffix = layer.name[len(block_prefix + "_conv"):]
        else:
            suffix = "_" + layer.name.split("_")[-1]

        # Build properties
        props = [f'withKey("name", prefix + "_conv{suffix}")']
        for k, v in layer.properties.items():
            if k == "name":
                continue
            if isinstance(v, bool):
                props.append(f'withKey("{k}", '
                             f'"{str(v).lower()}")')
            elif isinstance(v, str):
                props.append(f'withKey("{k}", "{v}")')
            else:
                props.append(f'withKey("{k}", {v})')

        # Determine input
        if len(layer.input_layers) == 1:
            inp = layer.input_layers[0]
            input_expr = tensor_vars.get(inp, prev_var)
        elif len(layer.input_layers) > 1:
            resolved = []
            for inp in layer.input_layers:
                resolved.append(tensor_vars.get(inp, inp))
            input_expr = "{" + ", ".join(resolved) + "}"
        else:
            input_expr = prev_var

        prop_str = ",\n    ".join(props)
        L.append(f'  LayerHandle {var_name}(createLayer('
                 f'"{layer.layer_type}", {{')
        L.append(f"    {prop_str}")
        L.append(f"  }}));")
        L.append(f"  Tensor {var_name}_out = {var_name}({input_expr});")

        tensor_vars[layer.name] = f"{var_name}_out"
        prev_var = f"{var_name}_out"

        # After a split layer, emit indexed output variables for each
        # getitem reference so downstream layers can use them.
        if layer.layer_type == "split" and layer.name == split_layer_name:
            L.append(f"")
            L.append(f"  // Indexed outputs from split/chunk")
            for gi_name in getitem_sorted:
                gi_idx = _getitem_index(gi_name)
                gi_var = f"chunk_{gi_idx}"
                L.append(f"  Tensor {gi_var} = "
                         f"{var_name}_out.output({gi_idx});")
                tensor_vars[gi_name] = gi_var

        L.append(f"")

    # Residual connection
    L.append(f"  // Conv residual connection")
    L.append(f"  Tensor residual = input.add({prev_var});")
    L.append(f"")

    # Pre-FFN norm
    L.append(f"  // Pre-FFN normalization")
    L.append(f'  LayerHandle ffn_norm(createLayer("rms_norm", {{')
    L.append(f'    withKey("name", prefix + "_ffn_norm"),')
    L.append(f'    withKey("epsilon", std::to_string(NORM_EPS)),')
    L.append(f'    withKey("packed", "false")')
    L.append(f"  }}));")
    L.append(f"  Tensor ffn_normed = ffn_norm(residual);")
    L.append(f"")

    # FFN
    L.append(f"  // Feed forward")
    L.append(f"  Tensor ffn_out = createMlp(layer_id, DIM, "
             f"INTERMEDIATE_SIZE, ffn_normed);")
    L.append(f"")

    # FFN residual
    L.append(f"  // FFN residual connection")
    L.append(f"  Tensor block_out = residual.add(ffn_out);")
    L.append(f"")
    L.append(f"  return block_out;")
    L.append(f"}}")
    L.append(f"")


def _emit_block_override(L, cname, s, diffs, norm_type):
    """Emit createTransformerDecoderBlock() override for post-norm models.

    Post-norm pattern: attn → residual add → LayerNorm → ffn → residual add → LayerNorm
    vs base pre-norm:  LayerNorm → attn → residual add → LayerNorm → ffn → residual add
    """
    L.append(f"Tensor")
    L.append(f"{cname}::createTransformerDecoderBlock(const int layer_id,")
    L.append(f"                                      Tensor input) {{")
    L.append(f"")
    L.append(f"  using ml::train::createLayer;")
    L.append(f"")

    if diffs["is_post_norm"]:
        # Post-norm: attention → residual → norm → ffn → residual → norm
        L.append(f"  // Self attention")
        L.append(f"  Tensor att_out =")
        L.append(f"    createAttention(layer_id, INIT_SEQ_LEN, NUM_HEADS, "
                 f"HEAD_DIM,")
        L.append(f"                    input, input, input);")
        L.append(f"")
        L.append(f"  // Attention residual + post-norm")
        L.append(f"  Tensor residual = input.add(att_out);")
        L.append(f'  LayerHandle att_norm(createLayer("{norm_type}", {{')
        L.append(f'    withKey("name", "layer" + std::to_string(layer_id) +'
                 f' "_attention_norm"),')
        L.append(f'    withKey("epsilon", std::to_string(NORM_EPS))')
        if norm_type == "layer_normalization":
            L.append(f'    , withKey("axis", 3)')
        elif norm_type == "rms_norm":
            L.append(f'    , withKey("packed", "false")')
        L.append(f"  }}));")
        L.append(f"  Tensor normed = att_norm(residual);")
        L.append(f"")
        L.append(f"  // Feed forward")
        L.append(f"  Tensor ffn_out = createMlp(layer_id, DIM, "
                 f"INTERMEDIATE_SIZE, normed);")
        L.append(f"")
        L.append(f"  // FFN residual + post-norm")
        L.append(f"  Tensor ffn_residual = normed.add(ffn_out);")
        L.append(f'  LayerHandle ffn_norm(createLayer("{norm_type}", {{')
        L.append(f'    withKey("name", "layer" + std::to_string(layer_id) +'
                 f' "_ffn_norm"),')
        L.append(f'    withKey("epsilon", std::to_string(NORM_EPS))')
        if norm_type == "layer_normalization":
            L.append(f'    , withKey("axis", 3)')
        elif norm_type == "rms_norm":
            L.append(f'    , withKey("packed", "false")')
        L.append(f"  }}));")
        L.append(f"  Tensor block_out = ffn_norm(ffn_residual);")
        L.append(f"")
        L.append(f"  return block_out;")
    else:
        # Pre-norm with LayerNorm instead of RMSNorm
        L.append(f"  // Pre-attention normalization")
        L.append(f'  LayerHandle att_norm(createLayer("{norm_type}", {{')
        L.append(f'    withKey("name", "layer" + std::to_string(layer_id) +'
                 f' "_attention_norm"),')
        L.append(f'    withKey("epsilon", std::to_string(NORM_EPS))')
        if norm_type == "layer_normalization":
            L.append(f'    , withKey("axis", 3)')
        L.append(f"  }}));")
        L.append(f"  Tensor normed = att_norm(input);")
        L.append(f"")
        L.append(f"  Tensor att_out =")
        L.append(f"    createAttention(layer_id, INIT_SEQ_LEN, NUM_HEADS, "
                 f"HEAD_DIM,")
        L.append(f"                    normed, normed, normed);")
        L.append(f"  Tensor residual = input.add(att_out);")
        L.append(f"")
        L.append(f'  LayerHandle ffn_norm(createLayer("{norm_type}", {{')
        L.append(f'    withKey("name", "layer" + std::to_string(layer_id) +'
                 f' "_ffn_norm"),')
        L.append(f'    withKey("epsilon", std::to_string(NORM_EPS))')
        if norm_type == "layer_normalization":
            L.append(f'    , withKey("axis", 3)')
        L.append(f"  }}));")
        L.append(f"  Tensor ffn_normed = ffn_norm(residual);")
        L.append(f"  Tensor ffn_out = createMlp(layer_id, DIM, "
                 f"INTERMEDIATE_SIZE, ffn_normed);")
        L.append(f"  Tensor block_out = residual.add(ffn_out);")
        L.append(f"")
        L.append(f"  return block_out;")

    L.append(f"}}")
    L.append(f"")


def _emit_attention_override(L, cname, s, attn_block, diffs):
    """Emit createAttention() override for models without RoPE or with bias."""
    L.append(f"Tensor")
    L.append(f"{cname}::createAttention(const int layer_id, int seq_len,")
    L.append(f"                         int n_heads, int head_dim,")
    L.append(f"                         Tensor query, Tensor key,")
    L.append(f"                         Tensor value) {{")
    L.append(f"")
    L.append(f"  using ml::train::createLayer;")
    L.append(f"")
    L.append(f'  auto V_name = "layer" + std::to_string(layer_id) + "_wv";')
    L.append(f'  auto K_name = "layer" + std::to_string(layer_id) + "_wk";')
    L.append(f'  auto Q_name = "layer" + std::to_string(layer_id) + "_wq";')
    L.append(f'  auto A_name = "layer" + std::to_string(layer_id) +'
             f' "_attention";')
    L.append(f'  auto O_name = "layer" + std::to_string(layer_id) +'
             f' "_attention_out";')
    L.append(f"")

    bias_prop = ('"disable_bias", "false"' if diffs["has_bias"]
                 else '"disable_bias", "true"')

    # V projection
    L.append(f"  // V projection")
    L.append(f'  LayerHandle v_proj(createLayer("fully_connected", {{')
    L.append(f'    withKey("name", V_name),')
    L.append(f'    withKey("unit", head_dim * n_heads / GQA_SIZE),')
    L.append(f'    withKey({bias_prop})')
    L.append(f"  }}));")
    L.append(f"  Tensor v = v_proj(value);")
    L.append(f"")

    # K projection
    L.append(f"  // K projection")
    L.append(f'  LayerHandle k_proj(createLayer("fully_connected", {{')
    L.append(f'    withKey("name", K_name),')
    L.append(f'    withKey("unit", head_dim * n_heads / GQA_SIZE),')
    L.append(f'    withKey({bias_prop})')
    L.append(f"  }}));")
    L.append(f"  Tensor k = k_proj(key);")
    L.append(f"")

    # Q projection
    L.append(f"  // Q projection")
    L.append(f'  LayerHandle q_proj(createLayer("fully_connected", {{')
    L.append(f'    withKey("name", Q_name),')
    L.append(f'    withKey("unit", head_dim * n_heads),')
    L.append(f'    withKey({bias_prop})')
    L.append(f"  }}));")
    L.append(f"  Tensor q = q_proj(query);")
    L.append(f"")

    # MHA core - with or without RoPE
    L.append(f"  // Attention core layer")
    L.append(f'  std::vector<std::string> attn_props = {{')
    L.append(f'    withKey("name", A_name),')
    L.append(f'    withKey("num_heads", n_heads),')
    L.append(f'    withKey("num_heads_kv", n_heads / GQA_SIZE),')
    L.append(f'    withKey("max_timestep", std::to_string(INIT_SEQ_LEN)),')
    L.append(f'    withKey("is_causal", IS_CAUSAL ? "true" : "false")')
    L.append(f"  }};")

    if not diffs["no_rope"]:
        L.append(f'  attn_props.push_back(withKey("rope_theta", ROPE_THETA));')
        L.append(f'  attn_props.push_back(withKey("max_position_embeddings",'
                 f' MAX_POSITION_EMBEDDINGS));')

    L.append(f'  LayerHandle attn(createLayer("mha_core", attn_props));')
    L.append(f"  Tensor a = attn({{q, k, v}});")
    L.append(f"")

    # O projection
    L.append(f"  // O projection")
    L.append(f'  LayerHandle o_proj(createLayer("fully_connected", {{')
    L.append(f'    withKey("name", O_name),')
    L.append(f'    withKey("unit", DIM),')
    L.append(f'    withKey({bias_prop})')
    L.append(f"  }}));")
    L.append(f"  Tensor o = o_proj(a);")
    L.append(f"")
    L.append(f"  return o;")
    L.append(f"}}")
    L.append(f"")


def _emit_test_factory(L, cname, s, need_variant, base_class, variant_name,
                       diffs=None):
    """Emit createTestModel() static factory for standalone testing."""
    if diffs is None:
        diffs = {}
    uses_layer_norm = diffs.get("uses_layer_norm", False)
    no_rope = diffs.get("no_rope", False)
    is_encoder_only = diffs.get("is_encoder_only", False)

    L.append(f"{cname} {cname}::createTestModel() {{")
    L.append(f"  // Minimal JSON config for testing")
    L.append(f"  json cfg;")
    L.append(f'  cfg["vocab_size"] = {s.vocab_size};')
    L.append(f'  cfg["hidden_size"] = {s.hidden_size};')
    L.append(f'  cfg["num_hidden_layers"] = {min(s.num_layers, 2)};')
    L.append(f'  cfg["num_attention_heads"] = {s.num_heads};')
    L.append(f'  cfg["num_key_value_heads"] = {s.num_kv_heads};')
    L.append(f'  cfg["head_dim"] = {s.head_dim};')
    L.append(f'  cfg["intermediate_size"] = {s.intermediate_size};')

    if not no_rope and s.rope_theta:
        L.append(f'  cfg["rope_theta"] = {int(s.rope_theta)};')

    norm_key = "layer_norm_eps" if uses_layer_norm else "rms_norm_eps"
    L.append(f'  cfg["{norm_key}"] = {s.norm_eps or 1e-6};')

    L.append(f'  cfg["tie_word_embeddings"] = '
             f'{"true" if s.tie_word_embeddings else "false"};')
    if s.max_position_embeddings:
        L.append(f'  cfg["max_position_embeddings"] = '
                 f'{s.max_position_embeddings};')

    if is_encoder_only:
        L.append(f'  cfg["is_causal"] = false;')

    L.append(f"")
    L.append(f"  json gen_cfg;")
    L.append(f'  gen_cfg["max_new_tokens"] = {0 if is_encoder_only else 1};')
    L.append(f"")
    L.append(f"  json nntr_cfg;")
    L.append(f'  nntr_cfg["init_seq_len"] = 8;')
    L.append(f'  nntr_cfg["batch_size"] = 1;')
    L.append(f'  nntr_cfg["model_tensor_type"] = "FP32-FP32";')
    L.append(f'  nntr_cfg["memory_swap"] = false;')
    L.append(f'  nntr_cfg["tokenizer_file"] = "";')
    L.append(f"")
    L.append(f"  return {cname}(cfg, gen_cfg, nntr_cfg);")
    L.append(f"}}")
    L.append(f"")
