// SPDX-License-Identifier: Apache-2.0
/**
 * Copyright (C) 2026 Samsung Electronics Co., Ltd. All Rights Reserved.
 *
 * @file   unittest_causallm_lfm2_moe_reference.cpp
 * @date   06 July 2026
 * @brief  Differential (cross-validation) tests for the LFM2-MoE CausalLM model.
 *
 * Compares nntrainer's LFM2-MoE output against golden fixtures generated by a
 * pure-PyTorch reference (generate_lfm2_moe_reference.py). The generic checks
 * live in causallm_test_utils; this file only binds the LFM2-MoE adapter and
 * the fixture name. Tests skip automatically when fixtures are absent.
 *
 * Only the FP32 differential check is provided: the router gate weight has
 * width num_experts (=4), which is not divisible by 32 and therefore cannot be
 * Q4_0-quantized via the save path (mirrors unittest_causallm_qwen3_moe).
 *
 * @see    https://github.com/nntrainer/nntrainer
 * @author Jungwon Lee <jungone.lee@samsung.com>
 * @bug    No known bugs except for NYI items
 */

#include <causallm_test_utils.h>

#include <gtest/gtest.h>

#include <lfm2_moe_causallm.h>

#include <memory>

namespace {

/**
 * @brief Differential model descriptor for the tiny LFM2-MoE fixture
 */
causallm_test::DifferentialModel lfm2MoeModel() {
  return {
    "lfm2_moe_tiny",
    [](causallm::json &cfg, causallm::json &gen_cfg, causallm::json &nntr_cfg) {
      return std::make_unique<
        causallm_test::CausalLMTestAdapter<causallm::Lfm2MoeCausalLM>>(
        cfg, gen_cfg, nntr_cfg);
    },
  };
}

/**
 * @brief FP32 prefill logits and greedy tokens match the reference
 */
TEST(Lfm2MoeDifferentialTest, FP32MatchesHFReference) {
  causallm_test::runFp32DifferentialChecks(lfm2MoeModel());
}

} // namespace
