// Auto-generated by TorchFX-to-NNTrainer converter
// Model: qwen3 (decoder_only)

#ifndef __TEST_MODEL_H__
#define __TEST_MODEL_H__

#include <climits>
#include <layer.h>
#include <model.h>

#include <reshaped_rms_norm.h>

using LayerHandle = std::shared_ptr<ml::train::Layer>;
using ModelHandle = std::unique_ptr<ml::train::Model>;

/**
 * @brief Qwen3CausalLM Class
 * @note Auto-generated from HuggingFace qwen3 model
 */
class Qwen3CausalLM {

public:
  Qwen3CausalLM();
  virtual ~Qwen3CausalLM() = default;

  /**
   * @brief Construct the model graph
   */
  virtual void constructModel();

  /**
   * @brief Initialize the model (register layers, construct, compile)
   */
  virtual void initialize();

  /**
   * @brief Get the underlying model handle
   */
  ModelHandle &getModel() { return model; }

protected:
  /**
   * @brief Create a Transformer DecoderBlock
   */
  virtual std::vector<LayerHandle>
  createTransformerDecoderBlock(const int layer_id, std::string input_name);

  /**
   * @brief Create Attention layers
   */
  virtual std::vector<LayerHandle>
  createAttention(const int layer_id, int seq_len, int n_heads, int head_dim,
                  std::string query_name, std::string key_name,
                  std::string value_name);

  /**
   * @brief Create Feed Forward layers
   */
  virtual std::vector<LayerHandle>
  createMlp(const int layer_id, int dim, int hidden_dim,
            std::string input_name);

  /**
   * @brief Register custom layers
   */
  virtual void registerCustomLayers();

  ModelHandle model;

  // Model constants
  unsigned int NUM_VOCAB = 1000;
  int DIM = 64;
  int NUM_LAYERS = 2;
  int NUM_HEADS = 4;
  int NUM_KV_HEADS = 2;
  int HEAD_DIM = 16;
  int INTERMEDIATE_SIZE = 128;
  float NORM_EPS = 1e-06f;
  unsigned int ROPE_THETA = 10000;
  bool TIE_WORD_EMBEDDINGS = false;
  int GQA_SIZE = 2;
  unsigned int SLIDING_WINDOW = UINT_MAX;
  unsigned int INIT_SEQ_LEN = 0;
  unsigned int NUM_TO_GENERATE = 0;
  unsigned int MAX_POSITION_EMBEDDINGS = 128;
};

#endif // __TEST_MODEL_H__
