// Auto-generated by TorchFX-to-NNTrainer converter
// Model: qwen3 (decoder_only)

#include "test_model.h"
#include <model.h>
#include <app_context.h>
#include <engine.h>

#include <embedding_layer.h>
#include <mha_core.h>
#include <rms_norm.h>
#include <reshaped_rms_norm.h>
#include <swiglu.h>

using ml::train::createLayer;

template <typename T>
static std::string withKey(const std::string &key, T val) {
  return key + "=" + std::to_string(val);
}

template <>
std::string withKey(const std::string &key, std::string val) {
  return key + "=" + val;
}

template <>
std::string withKey(const std::string &key, const char *val) {
  return key + "=" + std::string(val);
}

Qwen3CausalLM::Qwen3CausalLM() = default;

void Qwen3CausalLM::constructModel() {

  std::vector<LayerHandle> layers;

  // Create model
  model = ml::train::createModel(ml::train::ModelType::NEURAL_NET);

  // Input layer
    layers.push_back(createLayer("input", {
      withKey("name", "input0"),
      withKey("input_shape", "1:1:" + std::to_string(INIT_SEQ_LEN))
    }));

  // Embedding layer
  const std::string embedding_type = "embedding_layer";
    layers.push_back(createLayer("" + embedding_type + "", {
      withKey("name", "embedding0"),
      withKey("in_dim", NUM_VOCAB),
      withKey("out_dim", DIM)
    }));

  // Transformer blocks
  for (int i = 0; i < NUM_LAYERS; ++i) {
    std::string input_name = (i == 0) ? "embedding0"
      : "layer" + std::to_string(i - 1) + "_decoder_output";
    auto block = createTransformerDecoderBlock(i, input_name);
    layers.insert(layers.end(), block.begin(), block.end());
  }

  // Final normalization
    layers.push_back(createLayer("rms_norm", {
      withKey("name", "output_norm"),
      withKey("input_layers", "layer" + std::to_string(NUM_LAYERS - 1) + "_decoder_output"),
      withKey("epsilon", NORM_EPS),
      withKey("packed", "false")
    }));

  // LM head
  const std::string lmhead_type = "fully_connected";
    layers.push_back(createLayer("" + lmhead_type + "", {
      withKey("name", "output_of_causallm"),
      withKey("unit", NUM_VOCAB),
      withKey("disable_bias", "true"),
      withKey("input_layers", "output_norm")
    }));

  // Add layers to model
  for (auto &layer : layers) {
    model->addLayer(layer);
  }
}

std::vector<LayerHandle>
Qwen3CausalLM::createTransformerDecoderBlock(const int layer_id,
  std::string input_name) {

  std::vector<LayerHandle> layers;
  auto prefix = "layer" + std::to_string(layer_id);

  // Pre-attention normalization
    layers.push_back(createLayer("rms_norm", {
      withKey("name", prefix + "_attention_norm"),
      withKey("input_layers", input_name),
      withKey("epsilon", NORM_EPS),
      withKey("packed", "false")
    }));

  auto att_layer =
    createAttention(layer_id, INIT_SEQ_LEN, NUM_HEADS, HEAD_DIM,
                    prefix + "_attention_norm",
                    prefix + "_attention_norm",
                    prefix + "_attention_norm");

  layers.insert(layers.end(), att_layer.begin(), att_layer.end());

  // Attention residual connection
    layers.push_back(createLayer("addition", {
      withKey("name", prefix + "_self_attn_add"),
      withKey("input_layers", input_name + "," + prefix + "_attention_out")
    }));

  // Pre-FFN normalization
    layers.push_back(createLayer("rms_norm", {
      withKey("name", prefix + "_ffn_norm"),
      withKey("input_layers", prefix + "_self_attn_add"),
      withKey("epsilon", NORM_EPS),
      withKey("packed", "false")
    }));

  auto ffn_layer = createMlp(layer_id, DIM, INTERMEDIATE_SIZE,
                             prefix + "_ffn_norm");
  layers.insert(layers.end(), ffn_layer.begin(), ffn_layer.end());

  // FFN residual connection
    layers.push_back(createLayer("addition", {
      withKey("name", prefix + "_decoder_output"),
      withKey("input_layers", prefix + "_self_attn_add" + "," + prefix + "_ffn_down")
    }));

  return layers;
}

std::vector<LayerHandle>
Qwen3CausalLM::createAttention(const int layer_id, int seq_len, int n_heads,
                         int head_dim, std::string query_name,
                         std::string key_name, std::string value_name) {

  std::vector<LayerHandle> layers;

  auto Q = "layer" + std::to_string(layer_id) + "_wq";
  auto K = "layer" + std::to_string(layer_id) + "_wk";
  auto V = "layer" + std::to_string(layer_id) + "_wv";
  auto Q_norm = "layer" + std::to_string(layer_id) + "_q_norm";
  auto K_norm = "layer" + std::to_string(layer_id) + "_k_norm";
  auto A = "layer" + std::to_string(layer_id) + "_attention";
  auto O = "layer" + std::to_string(layer_id) + "_attention_out";

  // V layer
    layers.push_back(createLayer("fully_connected", {
      withKey("name", V),
      withKey("unit", head_dim * n_heads / GQA_SIZE),
      withKey("disable_bias", "true"),
      withKey("input_layers", value_name)
    }));

  // K layer
    layers.push_back(createLayer("fully_connected", {
      withKey("name", K),
      withKey("unit", head_dim * n_heads / GQA_SIZE),
      withKey("disable_bias", "true"),
      withKey("input_layers", key_name)
    }));

  // Q layer
    layers.push_back(createLayer("fully_connected", {
      withKey("name", Q),
      withKey("unit", head_dim * n_heads),
      withKey("disable_bias", "true"),
      withKey("input_layers", query_name)
    }));

  // K norm (reshaped RMS norm)
    layers.push_back(createLayer("reshaped_rms_norm", {
      withKey("name", K_norm),
      withKey("input_layers", K),
      withKey("packed", "false"),
      withKey("epsilon", NORM_EPS),
      withKey("feature_size", head_dim)
    }));

  // Q norm (reshaped RMS norm)
    layers.push_back(createLayer("reshaped_rms_norm", {
      withKey("name", Q_norm),
      withKey("input_layers", Q),
      withKey("packed", "false"),
      withKey("epsilon", NORM_EPS),
      withKey("feature_size", head_dim)
    }));

  // Attention core layer
    layers.push_back(createLayer("mha_core", {
      withKey("name", A),
      withKey("num_heads", n_heads),
      withKey("num_heads_kv", n_heads / GQA_SIZE),
      withKey("max_timestep", std::to_string(INIT_SEQ_LEN + NUM_TO_GENERATE)),
      withKey("sliding_window", SLIDING_WINDOW),
      withKey("rope_theta", ROPE_THETA),
      withKey("max_position_embeddings", MAX_POSITION_EMBEDDINGS),
      withKey("max_new_tokens", NUM_TO_GENERATE),
      withKey("input_layers", Q_norm + "," + K_norm + "," + V)
    }));

  // O layer
    layers.push_back(createLayer("fully_connected", {
      withKey("name", O),
      withKey("unit", DIM),
      withKey("disable_bias", "true"),
      withKey("input_layers", A)
    }));

  return layers;
}

std::vector<LayerHandle> Qwen3CausalLM::createMlp(
  const int layer_id, int dim, int hidden_dim,
  std::string input_name) {

  std::vector<LayerHandle> layers;

    layers.push_back(createLayer("fully_connected", {
      withKey("name", "layer" + std::to_string(layer_id) + "_ffn_up"),
      withKey("unit", hidden_dim),
      withKey("disable_bias", "true"),
      withKey("input_layers", input_name)
    }));

    layers.push_back(createLayer("fully_connected", {
      withKey("name", "layer" + std::to_string(layer_id) + "_ffn_gate"),
      withKey("unit", hidden_dim),
      withKey("disable_bias", "true"),
      withKey("input_layers", input_name)
    }));

    layers.push_back(createLayer("swiglu", {
      withKey("name", "layer" + std::to_string(layer_id) + "_ffn_swiglu"),
      withKey("input_layers", "layer" + std::to_string(layer_id) + "_ffn_up," + "layer" + std::to_string(layer_id) + "_ffn_gate")
    }));

    layers.push_back(createLayer("fully_connected", {
      withKey("name", "layer" + std::to_string(layer_id) + "_ffn_down"),
      withKey("unit", dim),
      withKey("disable_bias", "true"),
      withKey("input_layers", "layer" + std::to_string(layer_id) + "_ffn_swiglu")
    }));

  return layers;
}

void Qwen3CausalLM::registerCustomLayers() {
  auto &ct_engine = nntrainer::Engine::Global();
  auto app_context =
    static_cast<nntrainer::AppContext *>(ct_engine.getRegisteredContext("cpu"));

  try {
    app_context->registerFactory(nntrainer::createLayer<causallm::EmbeddingLayer>);
    app_context->registerFactory(nntrainer::createLayer<causallm::MHACoreLayer>);
    app_context->registerFactory(nntrainer::createLayer<causallm::RMSNormLayer>);
    app_context->registerFactory(nntrainer::createLayer<causallm::ReshapedRMSNormLayer>);
    app_context->registerFactory(nntrainer::createLayer<causallm::SwiGLULayer>);
  } catch (std::invalid_argument &e) {
    std::cerr << "failed to register factory, reason: " << e.what() << std::endl;
  }
}

void Qwen3CausalLM::initialize() {
  // Set default sequence length if not configured
  if (INIT_SEQ_LEN == 0) {
    INIT_SEQ_LEN = 8;
  }

  registerCustomLayers();
  constructModel();

  model->setProperty({
    withKey("batch_size", 1),
    withKey("epochs", "1"),
    withKey("model_tensor_type", "FP32-FP32")
  });

  if (model->compile(ml::train::ExecutionMode::INFERENCE)) {
    throw std::invalid_argument("Model compilation failed.");
  }

  if (model->initialize(ml::train::ExecutionMode::INFERENCE)) {
    throw std::invalid_argument("Model initialization failed.");
  }
}
