"""
Generates nntrainer-compatible C++ from the Compiler IR.

Two emission modes:

  MODEL_API           -- the original behavior. Walks graph.get_nodes()
                 and emits createLayer(...)/model->addLayer(...) calls
                 with an explicit input_layers property per node. Used
                 for every architecture with no matching semantic
                 adapter (graph.metadata doesn't set
                 emission_mode="causallm_component"), completely
                 unchanged.

  CAUSALLM_COMPONENT  -- used for the nntrainer_graph_ir produced by
                 the semantic lowering stage (api/lowering/nntrainer).
                 Rather than a standalone Tensor forward(Tensor input)
                 free function, this emits class-qualified method
                 overrides -- createAttention(), createMLP(),
                 createDecoderLayer(), registerCustomLayers() -- on a
                 Generated<Arch>Transformer / Generated<Arch>CausalLM
                 pair, matching how a real CausalLM integration project
                 structures per-architecture code (see
                 api/lowering/nntrainer/nntrainer_names.py for the
                 class-name convention). Produces a header and a
                 source file (generate_component()), not a single
                 buildModel()/main() -- there is no Model to compile()
                 here, and no standalone entry point: this code is
                 meant to be compiled *into* an existing CausalLM
                 project, not run by itself.

                 Requires every decoder layer to share the same
                 structural signature (graph.metadata["uniform_layers"],
                 set by the lowerer from
                 CausalLMIR.uniform_layer_signature()) -- createAttention
                 etc. are single virtual methods invoked once per
                 layer_id, so if the layers genuinely differ there is
                 no single method body that's correct for all of them.
                 generate_component() raises rather than silently
                 picking one layer as the template for every layer.
"""
import re
from dataclasses import dataclass
from enum import Enum

from api.graph.graph import Graph
from api.lowering.nntrainer.nntrainer_names import (
    generated_causal_lm_class, generated_transformer_class,
)


class CPPEmissionMode(Enum):
    MODEL_API = "model_api"
    CAUSALLM_COMPONENT = "causallm_component"


_LAYER_INDEX_RE = re.compile(r"(layers?[._])(\d+)(?=[._]|$)")


def _templatize_layer_index(text: str, layer_index: int) -> str:
    """'model.layers.0.self_attn.q_proj.weight' -> 'model.layers." +
    std::to_string(layer_id) + ".self_attn.q_proj.weight"' -- used when
    emitting the single reusable per-layer method bodies so a
    layer-0-only weight name becomes layer_id-parameterized C++."""
    def repl(m):
        if int(m.group(2)) != layer_index:
            return m.group(0)
        return f'{m.group(1)}" + std::to_string(layer_id) + "'
    return _LAYER_INDEX_RE.sub(repl, text)


def _readable_layer_index(text: str) -> str:
    """For comments only: 'model.layers.0.mlp.weight' -> 'model.layers.<layer_id>.mlp.weight'."""
    return _LAYER_INDEX_RE.sub(lambda m: f"{m.group(1)}<layer_id>", text)


@dataclass
class ComponentFiles:
    """Output of generate_component(): a header/source pair plus the
    class names used, so the caller (agents/cpp_generator_agent.py)
    knows what to name the files and can drop them straight into
    include/generated/ and src/generated/ (see doc item 3)."""
    header: str
    source: str
    header_filename: str
    source_filename: str
    transformer_class: str
    causal_lm_class: str
    architecture: str


_GENERATED_FILE_BANNER = (
    "/**\n"
    " * AUTO-GENERATED FILE.\n"
    " *\n"
    " * Generated by AI Compiler Workbench from a HuggingFace config.\n"
    " * Do not edit manually -- regenerate instead.\n"
    " *\n"
    " * Class/method signatures below are best-effort: they follow this\n"
    " * project's own Generated<Arch>Transformer/CausalLM naming pattern,\n"
    " * but have NOT been verified against a real transformer.h /\n"
    " * causal_lm.h / <arch>_causallm.h. A mismatched base class or\n"
    " * signature will fail to compile -- fix the signatures below to\n"
    " * match your actual base classes before relying on this file.\n"
    " */\n"
)


class CPPGenerator:
    def __init__(self, graph: Graph, mode: CPPEmissionMode = None):
        self.graph = graph
        self.mode = mode or (
            CPPEmissionMode.CAUSALLM_COMPONENT
            if graph.metadata.get("emission_mode") == "causallm_component"
            else CPPEmissionMode.MODEL_API
        )
        self._variable_names = {}  # node.id -> variable name, for supported nodes only

    def generate(self) -> str:
        """Single-string view of the generated code. For
        CAUSALLM_COMPONENT mode this is header+source concatenated for
        convenience (e.g. quick inspection, tests) -- callers that need
        to write two separate files should use generate_component()
        instead, which is what agents/cpp_generator_agent.py does."""
        if self.mode is CPPEmissionMode.CAUSALLM_COMPONENT:
            files = self.generate_component()
            return files.header + "\n\n" + files.source
        return self._generate_model_api()

    # ==================================================================
    # MODEL_API -- unchanged from prior behavior
    # ==================================================================

    # MODEL_API -- unchanged from prior behavior
    # ==================================================================

    def _generate_model_api(self) -> str:
        lines = []
        lines.extend(self._header())
        lines.extend(self._create_model())
        lines.extend(self._create_layers())
        lines.extend(self._footer())
        return "\n".join(lines)

    def _header(self):
        return [
            "#include <layer.h>",
            "#include <model.h>",
            "#include <iostream>",
            "#include <memory>",
            "",
            "using namespace ml::train;",
            "",
        ]

    def _create_model(self):
        # Wrapper is buildModel() -- deliberately NOT named createModel(), which
        # is the ccapi factory (ml::train::createModel) this body calls. Sharing
        # the name compiled only by overload-resolution luck and read as a bug.
        return [
            "std::unique_ptr<Model> buildModel()",
            "{",
            "    auto model = createModel(ModelType::NEURAL_NET);",
            "",
        ]

    def _create_layers(self):
        lines = []

        # Pre-compute variable names for every supported node so
        # input_layers can reference them regardless of declaration order.
        for node in self.graph.get_nodes():
            if node.supported:
                self._variable_names[node.id] = self._variable_name(node)

        for node in self.graph.get_nodes():
            variable = self._variable_names.get(node.id) or self._variable_name(node)

            if not node.supported:
                lines.append(
                    f"    // TODO(unsupported): {node.name} [{node.node_type}] "
                    f"-- {node.compatibility_reason}"
                )
                if node.weight_shape:
                    lines.append(
                        f"    // Weight: name={node.weight_name} shape={list(node.weight_shape)} "
                        f"dtype={node.weight_dtype} params={node.parameter_count}"
                    )
                lines.append(
                    f"    // Not emitted. Resolve this node before this file will build."
                )
                lines.append("")
                continue

            lines.append(f'    auto {variable} = createLayer("{node.node_type}");')
            lines.append(f'    {variable}->setProperty({{"name={node.name}"}});')

            for key, value in node.attributes.items():
                lines.append(f'    {variable}->setProperty({{"{key}={value}"}});')

            input_names = self._resolve_input_names(node)
            if input_names:
                joined = ",".join(input_names)
                lines.append(f'    {variable}->setProperty({{"input_layers={joined}"}});')

            if node.input_shape:
                lines.append(f"    // Input Shape : {node.input_shape}")
            if node.output_shape:
                lines.append(f"    // Output Shape: {node.output_shape}")
            if node.weight_shape:
                lines.append(
                    f"    // Weight: name={node.weight_name} shape={list(node.weight_shape)} "
                    f"dtype={node.weight_dtype} params={node.parameter_count}"
                )

            lines.append(f"    model->addLayer({variable});")
            lines.append("")

        return lines

    def _resolve_input_names(self, node, seen=None) -> list:
        """Walk back through node.inputs (direct predecessor ids). If a
        predecessor is itself unsupported/passthrough (no layer emitted),
        walk further back through *its* inputs to find the nearest
        real ancestor(s) -- so the wiring stays correct even around a
        TODO gap."""
        seen = seen or set()
        names = []
        for pred_id in getattr(node, "inputs", []) or []:
            if pred_id in seen:
                continue
            seen.add(pred_id)
            pred = self.graph.get_node(pred_id)
            if pred is None:
                continue
            if pred.id in self._variable_names:
                names.append(pred.name)
            else:
                names.extend(self._resolve_input_names(pred, seen))
        # de-dupe, preserve order
        out = []
        for n in names:
            if n not in out:
                out.append(n)
        return out

    def _footer(self):
        return [
            "    return model;",
            "}",
            "",
        ]

    def _variable_name(self, node):
        name = node.name.lower()
        name = (
            name.replace(".", "_")
                .replace("/", "_")
                .replace("-", "_")
                .replace(" ", "_")
        )
        return f"{name}_layer"

    # ==================================================================
    # CAUSALLM_COMPONENT -- class-integrated, semantic-lowering-driven
    # ==================================================================

    def generate_component(self) -> ComponentFiles:
        if not self.graph.metadata.get("uniform_layers"):
            raise ValueError(
                "CAUSALLM_COMPONENT generation requires every decoder layer "
                "to share the same structural signature (see "
                "CausalLMIR.uniform_layer_signature()) -- createAttention/"
                "createMLP are single virtual methods invoked once per "
                "layer_id, so a model whose layers genuinely differ has no "
                "single method body that's correct for every layer. Refusing "
                "to silently pick one layer as the template for all of them."
            )

        by_group = {}
        for node in self.graph.get_nodes():
            if node.group_id.startswith("decoder_"):
                by_group.setdefault(node.group_id, []).append(node)
        layer_ids = sorted(int(g.split("_", 1)[1]) for g in by_group)
        if not layer_ids:
            raise ValueError("target graph has no decoder-layer nodes to generate a component from")

        template_index = layer_ids[0]
        template_nodes = self._topo_sorted(by_group[f"decoder_{template_index}"])
        partitions = self._partition_layer_nodes(template_nodes, template_index)

        architecture = self.graph.metadata.get("architecture", "model")
        transformer_class = generated_transformer_class(architecture)
        causal_lm_class = generated_causal_lm_class(architecture)
        needs_reshaped_norm = any(n.node_type == "reshaped_rms_norm" for n in template_nodes)

        header = self._generate_component_header(architecture, transformer_class, causal_lm_class)
        source = self._generate_component_source(
            architecture, transformer_class, causal_lm_class,
            partitions, template_index, needs_reshaped_norm,
        )

        arch_slug = architecture.lower()
        return ComponentFiles(
            header=header,
            source=source,
            header_filename=f"generated_{arch_slug}_causallm.h",
            source_filename=f"generated_{arch_slug}_causallm.cpp",
            transformer_class=transformer_class,
            causal_lm_class=causal_lm_class,
            architecture=architecture,
        )

    def _partition_layer_nodes(self, ordered_nodes, template_index: int) -> dict:
        """Splits one decoder layer's topologically-sorted node list into
        the pieces createDecoderLayer/createAttention/createMLP each
        need. Boundaries are found by template_id suffix (set by the
        lowerer -- see api/lowering/nntrainer/lowerer.py) rather than
        semantic_type, since Q/K-norm nodes are semantic_type
        "normalization" but structurally belong inside the attention
        block, not alongside the decoder-level input/post norms."""
        def find(suffix):
            return next(n for n in ordered_nodes if n.template_id.endswith(suffix))

        input_norm = find(".input_norm")
        attention_residual = find(".attention_residual")
        post_norm = find(".post_attention_norm")
        mlp_residual = find(".mlp_residual")

        i_input_norm = ordered_nodes.index(input_norm)
        i_attn_res = ordered_nodes.index(attention_residual)
        i_post_norm = ordered_nodes.index(post_norm)
        i_mlp_res = ordered_nodes.index(mlp_residual)

        return {
            "input_norm": input_norm,
            "attention_nodes": ordered_nodes[i_input_norm + 1:i_attn_res],
            "attention_residual": attention_residual,
            "post_norm": post_norm,
            "mlp_nodes": ordered_nodes[i_post_norm + 1:i_mlp_res],
            "mlp_residual": mlp_residual,
            "template_index": template_index,
        }

    # ------------------------------------------------------------- header

    def _generate_component_header(self, architecture, transformer_class, causal_lm_class) -> str:
        base_transformer = transformer_class.replace("Generated", "", 1)
        base_causal_lm = causal_lm_class.replace("Generated", "", 1)
        arch_slug = architecture.lower()
        lines = [
            _GENERATED_FILE_BANNER,
            "#pragma once",
            "",
            f'#include <{arch_slug}_transformer.h>',
            f'#include <{arch_slug}_causallm.h>',
            "",
            "namespace causallm {",
            "",
            f"class {transformer_class} : public {base_transformer} {{",
            "public:",
            f"  using {base_transformer}::{base_transformer};",
            "",
            "  static void registerCustomLayers();",
            "",
            "protected:",
            "  // Signature is best-effort -- verify against the real",
            f"  // {base_transformer} base class and adjust if it differs.",
            "  Tensor createAttention(const int layer_id, Tensor hidden_states) override;",
            "  Tensor createMLP(const int layer_id, Tensor hidden_states) override;",
            "  Tensor createDecoderLayer(const int layer_id, Tensor hidden_states) override;",
            "};",
            "",
            f"class {causal_lm_class} : public {base_causal_lm} {{",
            "public:",
            f"  using {base_causal_lm}::{base_causal_lm};",
            "",
            "  void registerCustomLayers() override;",
            "};",
            "",
            "} // namespace causallm",
            "",
        ]
        return "\n".join(lines)

    # ------------------------------------------------------------- source

    def _generate_component_source(
        self, architecture, transformer_class, causal_lm_class,
        partitions, template_index, needs_reshaped_norm,
    ) -> str:
        base_causal_lm = causal_lm_class.replace("Generated", "", 1)
        lines = [
            _GENERATED_FILE_BANNER,
            "#include <llm_util.hpp>",
            "#include <model.h>",
            "",
            f"#include <generated/generated_{architecture.lower()}_causallm.h>",
            "",
            "#include <app_context.h>",
            "#include <engine.h>",
        ]
        if needs_reshaped_norm:
            lines.append("#include <reshaped_rms_norm.h>")
        lines += ["", "namespace causallm {", ""]

        lines += self._emit_attention_method(transformer_class, partitions, template_index)
        lines.append("")
        lines += self._emit_mlp_method(transformer_class, partitions, template_index)
        lines.append("")
        lines += self._emit_decoder_layer_method(transformer_class, partitions)
        lines.append("")
        lines += self._emit_register_custom_layers(transformer_class, needs_reshaped_norm)
        lines.append("")
        lines += [
            f"void {causal_lm_class}::registerCustomLayers() {{",
            f"  {base_causal_lm}::registerCustomLayers();",
            f"  {transformer_class}::registerCustomLayers();",
            "}",
            "",
            "} // namespace causallm",
            "",
        ]
        return "\n".join(lines)

    def _emit_attention_method(self, transformer_class, partitions, template_index) -> list:
        lines = [
            f"Tensor {transformer_class}::createAttention(const int layer_id, Tensor hidden_states)",
            "{",
        ]
        out = self._emit_component_body(
            lines, partitions["attention_nodes"], input_symbol="hidden_states",
            template_index=template_index, indent="  ",
        )
        lines.append(f"  return {out};")
        lines.append("}")
        return lines

    def _emit_mlp_method(self, transformer_class, partitions, template_index) -> list:
        lines = [
            f"Tensor {transformer_class}::createMLP(const int layer_id, Tensor hidden_states)",
            "{",
        ]
        out = self._emit_component_body(
            lines, partitions["mlp_nodes"], input_symbol="hidden_states",
            template_index=template_index, indent="  ",
        )
        lines.append(f"  return {out};")
        lines.append("}")
        return lines

    def _emit_decoder_layer_method(self, transformer_class, partitions) -> list:
        """Unlike createAttention/createMLP, this doesn't inline its
        sub-nodes -- it calls the two methods above by name, matching
        the doc's decoder-helper example (createAttention(...) is an
        opaque call here, not re-expanded), plus the two residual adds
        and two decoder-level norms that live directly in this method."""
        template_index = partitions["template_index"]
        input_norm = partitions["input_norm"]
        post_norm = partitions["post_norm"]
        attn_res = partitions["attention_residual"]
        mlp_res = partitions["mlp_residual"]

        lines = [
            f"Tensor {transformer_class}::createDecoderLayer(const int layer_id, Tensor hidden_states)",
            "{",
        ]

        in_sym = self._emit_single_layer_node(lines, input_norm, "hidden_states", template_index, indent="  ")
        lines.append(f"  Tensor attention_out = createAttention(layer_id, {in_sym});")
        lines.append("")

        ares_sym = self._variable_name(attn_res)
        lines.append(f'  LayerHandle {ares_sym}(createLayer("addition", {{"name={attn_res.name}"}}));')
        lines.append(f"  Tensor {ares_sym}_out = {ares_sym}({{hidden_states, attention_out}});")
        lines.append("")

        post_sym = self._emit_single_layer_node(lines, post_norm, f"{ares_sym}_out", template_index, indent="  ")
        lines.append(f"  Tensor mlp_out = createMLP(layer_id, {post_sym});")
        lines.append("")

        mres_sym = self._variable_name(mlp_res)
        lines.append(f'  LayerHandle {mres_sym}(createLayer("addition", {{"name={mlp_res.name}"}}));')
        lines.append(f"  Tensor {mres_sym}_out = {mres_sym}({{{ares_sym}_out, mlp_out}});")
        lines.append("")
        lines.append(f"  return {mres_sym}_out;")
        lines.append("}")
        return lines

    def _emit_register_custom_layers(self, transformer_class, needs_reshaped_norm) -> list:
        lines = [f"void {transformer_class}::registerCustomLayers()"]
        lines.append("{")
        if not needs_reshaped_norm:
            lines.append("  // This architecture uses only stock nntrainer layers -- nothing to register.")
            lines.append("}")
            return lines

        lines += [
            "  auto &engine = nntrainer::Engine::Global();",
            "",
            '  auto app_context = static_cast<nntrainer::AppContext *>(',
            '      engine.getRegisteredContext("cpu"));',
            "",
            "  try {",
            "    app_context->registerFactory(",
            "        nntrainer::createLayer<causallm::ReshapedRMSNormLayer>);",
            "  } catch (const std::invalid_argument &error) {",
            '    std::cerr << "Failed to register custom layer: " << error.what() << std::endl;',
            "  }",
            "}",
        ]
        return lines

    # ------------------------------------------------------------ shared

    def _topo_sorted(self, nodes):
        """Nodes within one decoder-layer group, in the order the
        lowerer built them (insertion order == dataflow order for this
        graph -- no diamond needs re-sorting beyond that)."""
        by_id = {n.id: n for n in nodes}
        ordered, seen = [], set()

        def visit(n):
            if n.id in seen:
                return
            seen.add(n.id)
            for pred_id in n.inputs:
                if pred_id in by_id:
                    visit(by_id[pred_id])
            ordered.append(n)

        for n in nodes:
            visit(n)
        return ordered

    def _pred_output_symbols(self, pred, base_symbol: str) -> list:
        """The C++ tensor-symbol token(s) a downstream node should use to
        reference `pred`'s output. Almost every node has exactly one;
        kv_cache_placeholders is the one multi-output exception (its
        emitted C++ destructures into cache_k/cache_v via `auto [x, y] =
        ...`), so anything consuming it (mha_core) needs both tokens,
        not a single made-up "_out" that was never declared."""
        if pred.node_type == "kv_cache_placeholders":
            return [f"{base_symbol}_k", f"{base_symbol}_v"]
        return [f"{base_symbol}_out"]

    def _emit_single_layer_node(self, lines, node, input_symbol, template_index, indent="  ") -> str:
        """Emits one node whose only input is the method's own parameter
        (used for the decoder-level input/post norms, which never
        depend on anything inside createAttention/createMLP)."""
        symbol = self._variable_name(node)
        name_t = _templatize_layer_index(node.name, template_index)
        props = [f'"name={name_t}"'] + [f'"{k}={v}"' for k, v in node.attributes.items()]
        lines.append(f'{indent}LayerHandle {symbol}(createLayer("{node.node_type}", {{{", ".join(props)}}}));')
        lines.append(f"{indent}Tensor {symbol}_out = {symbol}({input_symbol});")
        if node.weight_name:
            lines.append(f"{indent}// Weight: {_readable_layer_index(node.weight_name)}")
        lines.append("")
        return f"{symbol}_out"

    def _emit_component_body(self, lines, nodes, input_symbol, template_index, indent="  ") -> str:
        """Emits a self-contained node list (createAttention's or
        createMLP's internals) using `input_symbol` as the C++
        expression for anything that depends on the method's own
        parameter rather than another node inside this same list, and
        the real intra-list dataflow (including kv_cache_placeholders'
        two-symbol destructuring) everywhere else. Returns the final
        node's output symbol, i.e. what the method should `return`."""
        node_ids = {n.id for n in nodes}
        prev_symbol = input_symbol

        for node in nodes:
            symbol = self._variable_name(node)

            if node.node_type == "kv_cache_placeholders":
                num_kv_heads = node.attributes.get("num_kv_heads", 0)
                lines.append(f"{indent}auto [{symbol}_k, {symbol}_v] = createKVCachePlaceholders(layer_id, {num_kv_heads});")
                lines.append("")
                continue  # not chained via prev_symbol -- consumers read both symbols by name

            out_symbol = f"{symbol}_out"
            name_t = _templatize_layer_index(node.name, template_index)
            props = [f'"name={name_t}"'] + [f'"{k}={v}"' for k, v in node.attributes.items()]
            lines.append(f'{indent}LayerHandle {symbol}(createLayer("{node.node_type}", {{{", ".join(props)}}}));')

            input_symbols = []
            for pid in node.inputs:
                pred = self.graph.get_node(pid)
                if pred is None:
                    continue
                if pred.id in node_ids:
                    input_symbols.extend(self._pred_output_symbols(pred, self._variable_name(pred)))
                else:
                    # Anything outside this node list that something in it
                    # depends on is the method's own parameter (the
                    # normalized hidden state createAttention/createMLP
                    # were called with) -- never a node from a different
                    # method or a different decoder layer.
                    input_symbols.append(input_symbol)
            if not input_symbols:
                input_symbols = [prev_symbol]

            if len(input_symbols) == 1:
                lines.append(f"{indent}Tensor {out_symbol} = {symbol}({input_symbols[0]});")
            else:
                joined = ", ".join(input_symbols)
                lines.append(f"{indent}Tensor {out_symbol} = {symbol}({{{joined}}});")

            if node.weight_name:
                lines.append(f"{indent}// Weight: {_readable_layer_index(node.weight_name)}")
            lines.append("")
            prev_symbol = out_symbol

        return prev_symbol

    def save(self, output_file: str):
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(self.generate())
